### ISSUE TITLE
ncurses corrupt inside Docker

### ISSUE THREAD

**Issue by altklug** [mimblewimble/grin#2056] opened 2018-11-30 08:27 UTC
I get a corrupt ncurses inside Docker.

I tried setting TERM to xterm but it didn't help.

I also tried setting the number of rows and columns using:
```
-e COLUMNS="`tput cols`" -e LINES="`tput lines`"
```
in my docker invocation, as suggested here: https://github.com/moby/moby/issues/33794
but that didn't work either.

![image](https://user-images.githubusercontent.com/45346511/49277466-02f2c780-f4c5-11e8-9414-e25fad013e3e.png)

**Comment by quentinlesceller** [comment] 2018-11-30 14:29
Based on the screenshot you provided it looks like a ‘locales’ issue. Basically running ‘locale-gen’ with ‘US-UTF8’ would fix it. Let me see if I can reproduce your issue.

**Comment by quentinlesceller** [comment] 2018-11-30 16:09
Update: Looks like a `locale` issue on you machine. You should run something like `sudo locale-gen en_US.UTF-8` to fix it. Closing this since it's not grin related.

**Closed by quentinlesceller** 2018-11-30 16:09 UTC
