### ISSUE TITLE
runtime error on SIGINT

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#1579] opened 2018-09-22 19:43 UTC
```
^CSep 22 19:40:12.685 WARN Received SIGINT (Ctrl+C) or SIGTERM (kill).
Sep 22 19:40:12.691 WARN sync: no peers available, disabling sync
Sep 22 19:40:13.685 WARN Shutting down...
Sep 22Thread 'peer' panicked with message:
"called `Option::unwrap()` on a `None` value"
See grin.log for further details.
 19:40:13.715 ERRO 
thread 'peer' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:345stack backtrace:
   0:     0x55b899b1270c - backtrace::backtrace::trace::h97c9c167afe4715f
   1:     0x55b899b124c2 - <backtrace::capture::Backtrace as core::default::Default>::default::hcc49c56acd9f8793
   2:     0x55b899b12538 - backtrace::capture::Backtrace::new::hbcc3e919ce2efbce
   3:     0x55b899aab79e - grin_util::logger::send_panic_to_log::{{closure}}::hac4b255e634a79ee
   4:     0x55b899c206d3 - std::panicking::rust_panic_with_hook::hba05450791beb933
                        at libstd/panicking.rs:479
   5:     0x55b899c20279 - std::panicking::continue_panic_fmt::hd2a4220d2e2291e2
                        at libstd/panicking.rs:390
   6:     0x55b899c20175 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55b899c7b73b - core::panicking::panic_fmt::h2c383e888dce42c0
                        at libcore/panicking.rs:77
   8:     0x55b899c7b66a - core::panicking::panic::h14eb4ebea7b4bf80
                        at libcore/panicking.rs:52
   9:     0x55b8996bc47b - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::headers_received::h2b4ee4729e7a0806
  10:     0x55b89996a5dd - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::headers_received::hce6b14f2cebc2536
  11:     0x55b8999586c8 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::headers_received::h3b320da6b6aab71a
  12:     0x55b8999928e0 - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::heaca019acd21e74d
  13:     0x55b899960486 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb89dd7fbe3428712
  14:     0x55b899961928 - std::panicking::try::do_call::h50a754c9138776b9
  15:     0x55b899c44c89 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  16:     0x55b89998b7cd - <F as alloc::boxed::FnBox<A>>::call_box::ha1c14b8365637878
  17:     0x55b899c22d2a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h940efee7335c8f36
                        at /checkout/src/liballoc/boxed.rs:652
                         - std::sys_common::thread::start_thread::hac18b9ed82bd359d
                        at libstd/sys_common/thread.rs:24
  18:     0x55b899c20ca5 - std::sys::unix::thread::Thread::new::thread_start::ha15fdd35f58285a3
                        at libstd/sys/unix/thread.rs:90
  19:     0x7ff179187493 - start_thread
  20:     0x7ff178cb2ace - __clone
  21:                0x0 - <unknown>

```

**Comment by haarts** [comment] 2018-10-19 13:33
Can you tell us how you started Grin? And on which platform you're running? Perhaps even tell us which version of Grin (a Git SHA)? 
I was unable to reproduce.

**Comment by jaspervdm** [comment] 2018-10-19 13:41
This type of error typically appears when using an outdated configuration file.

**Comment by jakecraige** [comment] 2018-11-25 00:41
SHA/version would be helpful here. I was going to take a look at this but the code path has changed a good bit since this issue was created so it would be hard to pin down this exact occurance.

Here's what I've found so far, using `0.0.0-pre.0.3.0` (released a few days after this was created), as a reference point.

The flow for the server stopping goes `server stop -> p2p peers stop -> p2p stop each connected peer`. All starting [here](https://github.com/mimblewimble/grin/blob/e55c3d2ec989ec633359c401c163429f04b440d2/servers/src/grin/server.rs#L464).

There's two unsafe paths here. First we have this where it unwraps some `RwLocks`. I'm not very familiar with the `LockResult` it returns but docs state that it could be an error if the thread that held it crashes. Since we're shutting down it seems possible this could be related.

https://github.com/mimblewimble/grin/blob/e55c3d2ec989ec633359c401c163429f04b440d2/p2p/src/peers.rs#L482-L486

Secondly we have the peer itself closing it's connection.

https://github.com/mimblewimble/grin/blob/e55c3d2ec989ec633359c401c163429f04b440d2/p2p/src/peer.rs#L325

The connection is only initialized when the [start function](https://github.com/mimblewimble/grin/blob/e55c3d2ec989ec633359c401c163429f04b440d2/p2p/src/peer.rs#L97) is called so if we were to call stop before then, this would crash.

Looking into how those are initialized. We have two places, and it turns out that there could be a race condition there. I'm not sure how long start normally takes or if there's some path where the process could have been killed between those lines finishing, but that would cause this panic.

https://github.com/mimblewimble/grin/blob/e55c3d2ec989ec633359c401c163429f04b440d2/p2p/src/serv.rs#L221-L223
https://github.com/mimblewimble/grin/blob/e55c3d2ec989ec633359c401c163429f04b440d2/p2p/src/serv.rs#L189-L193

---

Now, that's all the old code. When we look at the old code, basically all of those possibilities have been fixed.

No longer unwrapping `RwLock`s

https://github.com/mimblewimble/grin/blob/af595fa0fc5bc7e42117b6e43e93a27305c4da4e/p2p/src/peers.rs#L435-L438

And starting up the connection before adding it to list of peers:

https://github.com/mimblewimble/grin/blob/af595fa0fc5bc7e42117b6e43e93a27305c4da4e/p2p/src/serv.rs#L148-L150
https://github.com/mimblewimble/grin/blob/af595fa0fc5bc7e42117b6e43e93a27305c4da4e/p2p/src/serv.rs#L177-L178

Assuming it could have been one of those conditions, it seems like this is probably fixed

**Comment by ignopeverell** [comment] 2018-11-25 23:49
Thanks for looking into it @jakecraige, going to close then as it's likely fixed.

**Closed by ignopeverell** 2018-11-25 23:49 UTC
Labels: bug, good first issue
