### ISSUE TITLE
funds lost (?) after cancelling tx that was stalling for 24 hours (with other successful rx and tx in between)

### ISSUE THREAD

**Issue by aleqx** [mimblewimble/grin#2551] opened 2019-02-09 14:12 UTC
it seems I lost 14.977 grin :( ... but I hope someone here knows a way to get it back (I already did a `wallet check` and also tried `wallet restore`, also upgraded to 1.0.1 and tried `wallet check` and `wallet restore` again). 

I was running grin 1.0.0 on Ubuntu 16.04 when I made an http-based deposit to Bibox about 24h ago, though it was not getting confirmed even after many hours (chain height was advancing). In the meantime I made other tx and rx transactions from/to the same wallet. After 24h the Bibox deposit It was not getting confirmed at all so I decided to cancel it using `grin wallet cancel --txid <txid>`.

It said it's cancelled but the 14.977 grin were never returned to my wallet :(. Here are all the transactions from/to this wallet since the Bibox deposit was triggered (times are UTC+2):

![](https://i.gyazo.com/66086a81261c1d58f6f35be46b0272ed.png)

Here's the output of `wallet txs -i 109`:

![](https://i.gyazo.com/c422cb9efafff4838e5005ad87ebc3b5.png)

The wallet balance is 69.985, when it should be 69.985 + 14.977 = 84.962:

![](https://i.gyazo.com/86692e09723a68cfac2d70f7f135a1a5.png)

**NOTE:** You can see in the list of transaction above there was another cancelled transaction (index 112). That one was "weird" but I didn't lose those funds. It was a file-based deposit to Tradeogre that I made and which was also stalling and was getting no confirmations despite the chain height advancing. I didn't cancel it myself but ran a `wallet check` and it cancelled it itself and returned the funds.

I since upgraded to 1.0.1 and tried a check and restore, to no avail.

Is there a way to get back my 14.977 grin or should I kiss them good bye?

**EDIT:** Checking the tx output of tx index 109 (the cancelled 14.977 grin transaction) on the explorer I see: https://grinscan.net/output/0862a116dc219ac2824178597a82acd0a5e884b98fdef83e7ab7aca084cd1ff99e

... which says it was spent in block 34180, which was yesterday, and yet I cancelled it today.

I'm lost :(

**P.S.** I dumped that problematic transaction to a file using `repost -i 109 -m dumped-failed-deposit.tx`. I don't want to repost it to the chain until a dev can confirm what is safe to do at this stage (also, Bibox doesn't have a file-based slate interface for me to finalize it at the other end and their tech support has been deplorable until now).

**Comment by aleqx** [comment] 2019-02-09 14:20
Interestingly, Bibox is still showing it as `Pending`:

![](https://i.gyazo.com/98bd61f390dbb67f915d080247f5a841.png)

... where you can see 2 other deposits made to Bibox. The `Success`ful one of 40.0 grin was made from the same wallet (from the above post):

![](https://i.gyazo.com/5f34bf2d23900d0ec685e83ad20f74e5.png)

.. whereas the `Fail`ed one of 40 grin was made directly from Bitforex.

Interesting that it says `Fail` for the 40 grin one from Bitforex, but `Pending` for the 14.977 grin one from my wallet. Does that mean there is still hope for my 14.977 grin?

**Comment by aleqx** [comment] 2019-02-09 15:53
I dumped that problematic transaction to a file using `repost -i 109 -m dumped-failed-deposit.tx`. I don't want to repost it to the chain until a dev can confirm what is safe to do at this stage (also, Bibox doesn't have a file-based slate interface for me to finalize it at the other end and their tech support has been deplorable until now).

**Comment by aleqx** [comment] 2019-02-09 16:41
Checking the tx output of the cancelled 14.977 grin transaction on the explorer I see:  https://grinscan.net/output/0862a116dc219ac2824178597a82acd0a5e884b98fdef83e7ab7aca084cd1ff99e

... which says it was spent in block 34180, which was yesterday, and yet I cancelled it today.

I'm lost :(

**Comment by mcdallas** [comment] 2019-02-11 16:02
It seems that the transaction confirmed normally but your wallet failed to identify it as confirmed because there was no change output (notice the amount credited = 0 in your tx). 

Related #2558

**Comment by hashmap** [comment] 2019-03-05 12:05
Duplicate of https://github.com/mimblewimble/grin/issues/2558

**Comment by quentinlesceller** [comment] 2019-03-26 14:22
Duplicate of #2558, closing.

**Closed by quentinlesceller** 2019-03-26 14:22 UTC
