### ISSUE TITLE
node doesnt start

### ISSUE THREAD

**Issue by zod11** [mimblewimble/grin#2721] opened 2019-04-01 15:38 UTC
When I try to start a node on a fresh server it soesn't start

**To Reproduce**
1. Install a node with prereq (rust 1.33)
(use rustup- i.e. curl https://sh.rustup.rs -sSf | sh; source $HOME/.cargo/env)
mkdir -p ~/grin
tar xzf grin-v1.0.0-479973573-linux-amd64.tgz -C ~/grin

2. prepare environment

echo export 'PATH=~/grin:$PATH' >> ~/.bashrc
source ~/.bashrc

3. run grin

nothing happens

Logfile:

```
20190401` 15:25:27.921 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190401 15:25:27.921 INFO grin - Using configuration file at /home/zod1/.grin/main/grin-server.toml
20190401 15:25:27.921 INFO grin - This is Grin version 1.1.0-beta.1 (git 1.1.0-beta.1), built for x86_64-unknown-linux-gnu by rustc 1.33.0 (2aa4c46cf 2019-02-28).
20190401 15:26:09.607 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190401 15:26:09.607 INFO grin - Using configuration file at /home/zod1/.grin/main/grin-server.toml
20190401 15:26:09.607 INFO grin - This is Grin version 1.1.0-beta.1 (git 1.1.0-beta.1), built for x86_64-unknown-linux-gnu by rustc 1.33.0 (2aa4c46cf 2019-02-28).
20190401 15:26:09.607 WARN grin::cmd::server - Starting GRIN in UI mode...
20190401 15:26:09.607 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190401 15:26:09.608 INFO grin_store::lmdb - Resized database from 1048576 to 134217728
20190401 15:26:09.713 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner:

Other Error: output vs rproof MMRs different sizes })': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::hf7ab53c8e0b02861 (0x5650522e30f0)
   1: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x565052408be9)
             at src/libstd/panicking.rs:482
   2: std::panicking::continue_panic_fmt::h3557b3c3fa21b47b (0x565052408691)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x565052408575)
             at src/libstd/panicking.rs:312
   4: core::panicking::panic_fmt::h74ee8034b317ceed (0x5650524233bc)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::hffe15a3c4305f289 (0x565051cb9eb9)
   6: grin::cmd::server::start_server::h60daae9653a1649c (0x565051c6ebbb)
   7: grin::cmd::server::server_command::h9595d94d31f59738 (0x565051c6f2e2)
   8: grin::real_main::h54160841d21d6642 (0x565051cb2b9e)
   9: grin::main::h726b46fb899da6db (0x565051cb1b55)
  10: std::rt::lang_start::{{closure}}::h25c488057ca7de7b (0x565051c79ed2)
  11: std::rt::lang_start_internal::{{closure}}::h8ad4264c6b68797c (0x565052408512)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h7a0381557c6c2cee
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic (0x56505240efa9)
             at src/libpanic_unwind/lib.rs:92
  13: std::panicking::try::h72cb0fef6e9c0ab1 (0x565052409065)
             at src/libstd/panicking.rs:276
      std::panic::catch_unwind::hbff071ae76e6f224
             at src/libstd/panic.rs:388
      std::rt::lang_start_internal::he0d8d06abc6f912f
             at src/libstd/rt.rs:48
  14: main (0x565051cb31e1)
  15: __libc_start_main (0x7fc846e412e0)
  16: <unknown> (0x565051c57200)
  17: <unknown> (0x0)'
```

**Desktop (please complete the following information):**
 - OS: linux
 - Version debian stretch

**Comment by hashmap** [comment] 2019-04-01 17:50
@zod11 duplicate of https://github.com/mimblewimble/grin/issues/2334  the possible reason https://github.com/mimblewimble/grin/issues/2494

Workaround -  you don't need to install Rust if you use the binary. However, since you have it installed already you can build grin from the sources, in this case a binary you build will work on your machine.

**Closed by hashmap** 2019-04-01 17:50 UTC
