### ISSUE TITLE
Stratum server panics when fails to connect to wallet server

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1000] opened 2018-04-24 15:59 UTC
On https://github.com/mimblewimble/grin/commit/2b2e13be636eb15445111b3c14b15f7e7e2ec028.
When the wallet is offline and stratum server enabled, the stratum server panic with the following message:
```
Apr 24 11:56:51.626Thread 'stratum_server' panicked with message:
"cannot recursively call into `Core`"
See grin.log for further details.
 ERRO 
thread 'stratum_server' panicked at 'cannot recursively call into `Core`': libcore/option.rs:917stack backtrace:
   0:        0x1009f0e1e - backtrace::backtrace::trace::hf461bc488209c74d
   1:        0x1009ef32c - backtrace::capture::Backtrace::new::he34888423e6125a4
   2:        0x100972ec3 - grin_util::logger::send_panic_to_log::_$u7b$$u7b$closure$u7d$$u7d$::hfd455fadec7b8d28
   3:        0x100aaf150 - std::panicking::rust_panic_with_hook::hfb431ab23831437f
   4:        0x100aaef6e - std::panicking::begin_panic::h083a5eed938a1a63
   5:        0x100aaeec2 - std::panicking::begin_panic_fmt::h2d93f83eaf48dbcd
   6:        0x100aaee22 - rust_begin_unwind
   7:        0x100aeaea5 - core::panicking::panic_fmt::he42c3e63824a6609
   8:        0x100aeaf18 - core::option::expect_failed::h665835dead85fc51
   9:        0x1002785af - tokio_core::reactor::Core::run::h04f928e8214f51c3
  10:        0x100251e09 - _$LT$F$u20$as$u20$tokio_retry..action..Action$GT$::run::ha3e8479398cbc4d9
  11:        0x1002cc7a2 - _$LT$tokio_retry..future..RetryIf$LT$I$C$$u20$A$C$$u20$C$GT$$u20$as$u20$futures..future..Future$GT$::poll::h8a145509a632ec51 (.llvm.16767459630178162227)
  12:        0x1002c562f - futures::task_impl::std::set::hd6ec89a2a95a84ab
  13:        0x1002a060d - _$LT$futures..future..lazy..Lazy$LT$F$C$$u20$R$GT$$u20$as$u20$futures..future..Future$GT$::poll::hbd6140546a13c932
  14:        0x1002c59bf - futures::task_impl::std::set::he52410ecfbe9cf05
  15:        0x10024d7af - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::haa87acb81e7842c0
  16:        0x100299048 - _$LT$tokio..executor..current_thread..Entered$LT$$u27$a$C$$u20$P$GT$$GT$::block_on::haa15d65b546ab844
  17:        0x10024e508 - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::hd7a425db2165aca3
  18:        0x10024e135 - _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::hb6b0b71afd83ceca
  19:        0x1002f5838 - _$LT$scoped_tls..ScopedKey$LT$T$GT$$GT$::set::h7cd3308624e0cc72
  20:        0x10027ab2f - tokio_core::reactor::Core::run::h6b902d86ce982a80
  21:        0x10025de66 - grin_wallet::client::create_coinbase::hd79ee1fea1ffc7e2
  22:        0x1001fc41f - grin_servers::mining::mine_block::build_block::hfe378ee8f73e82f9
  23:        0x1001fb7cc - grin_servers::mining::mine_block::get_block::h1cfda2c19cb6d923
  24:        0x1001c1c45 - grin_servers::mining::stratumserver::StratumServer::run_loop::h695a3c6c7528cfa1
  25:        0x1001f5a5a - std::sys_common::backtrace::__rust_begin_short_backtrace::h4bc7b34e9834ee6b
  26:        0x1001c74cd - std::panicking::try::do_call::h531591af4784764b (.llvm.13673783893144299434)
  27:        0x100abdfce - __rust_maybe_catch_panic
  28:        0x1001b64d3 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h01841ce5a829aa3c
  29:        0x100ab344b - std::sys::unix::thread::Thread::new::thread_start::h2f926488e05dc513
  30:     0x7fff5085c660 - _pthread_body
  31:     0x7fff5085c50c - _pthread_start
```

Full log [here](https://pastebin.com/Cv0A6YF8).

**Comment by bladedoyle** [comment] 2018-04-24 18:26
Verified: I am able to reproduce this issue when wallet listener is not running.

**Comment by bladedoyle** [comment] 2018-04-24 20:43
The failure is here:

 grin_wallet::client::retry_backoff_forever
 wallet/src/client.rs:63
        let res = core.run(retry_future).unwrap();

**Comment by bladedoyle** [comment] 2018-04-24 20:44
NOTE:  This appears to be a duplicate of existing issue:  https://github.com/mimblewimble/grin/issues/768

**Comment by quentinlesceller** [comment] 2018-04-24 20:49
Okay maybe a ```match``` will do here.

**Closed** 2018-04-25 15:48 UTC
Labels: enhancement
