### ISSUE TITLE
grin-server.log reject block entries

### ISSUE THREAD

**Issue by goodthebest** [mimblewimble/grin#2561] opened 2019-02-12 00:08 UTC
Hi, 
1. **Circled red**  
Sometimes there are no peers to sync, are there any peers available I can manually add to grin?

2. **Circled blue**
i've enabled mining and mining server and looking at grin-server.log I am getting constantly these, why it says block rejected even though no one is mining at my node or it's normal log, can anyone please shed a light?

![image](https://user-images.githubusercontent.com/1715740/52602348-b5f38000-2e7b-11e9-815e-a406e4f35897.png)

**Comment by hashmap** [comment] 2019-02-12 11:08
Perhaps a duplicate of https://github.com/mimblewimble/grin/issues/2495

**Closed** 2019-02-12 22:56 UTC
