### ISSUE TITLE
The node stops synchronizing when following error occurs.

### ISSUE THREAD

**Issue by kostia07** [mimblewimble/grin#2495] opened 2019-01-30 16:46 UTC
20190130 16:58:18.232 DEBUG grin_chain::pipe - pipe: process_block 0000039cc9ff at 17795 [in/out/kern: 8/11/6]
20190130 16:58:18.234 DEBUG grin_chain::txhashset::txhashset - Error returned, discarding txhashset extension: Already Spent: Commitment(09a1088835e30cfc402ecf6a10850a4f48728dc555632ac9ec53da70eb5603c156) 
 Cause: Unknown 
 Backtrace: 
20190130 16:58:18.234 INFO grin_chain::chain - Rejected block 0000039cc9ff at 17795: Error { inner: 

Already Spent: Commitment(09a1088835e30cfc402ecf6a10850a4f48728dc555632ac9ec53da70eb5603c156) }
20190130 16:58:18.234 DEBUG grin_servers::common::adapters - process_block: block 0000039cc9ff refused by chain: Other Error: Error { inner: 

Already Spent: Commitment(09a1088835e30cfc402ecf6a10850a4f48728dc555632ac9ec53da70eb5603c156) }
20190130 16:58:18.234 DEBUG grin_servers::grin::sync::body_sync - block_sync: 17794/21389 requesting blocks [0000039cc9ff] from 34 peers

**Comment by hashmap** [comment] 2019-01-31 09:59
@kostia07 could you share your  ~/.grin/main/chain_data/ as an archive?
Your node rejects a perfectly valid input https://grinscan.net/output/09a1088835e30cfc402ecf6a10850a4f48728dc555632ac9ec53da70eb5603c156 in block 17795 so can't progress after that.

**Comment by antiochp** [comment] 2019-02-01 15:22
I'm _guessing_ that this is a corrupted `chain_data` such that we're reading the _wrong_ commitment out of the PMMR. This could happen if the `leaf_set` was corrupted (we calculate the offset incorrectly and read the wrong offset bytes from the file).

I'd be _very_ surprised if this is actually what it suggests from the error itself - we just incorrectly think something is `Already Spent` because the data is corrupted.

Just guessing and thinking out loud though. We have seen things similar to this in the past.

**Comment by hashmap** [comment] 2019-02-15 22:57
Got this issue on my node. Unfortunately in this state a node produces a lot of log messages, so thanks to log rotation I have logs only for last 5 hours, which is not enough to find when and why it happened

**Comment by hashmap** [comment] 2019-02-15 23:08
Currently I see ~20 peers, 4 of them stuck at different heights - 10809, 2703, 38692, 44507. I suspect this bug may be the reason

**Comment by antiochp** [comment] 2019-02-16 11:00
> thanks to log rotation I have logs only for last 5 hours

Previous logs are zipped up and archived though right?

**Comment by hashmap** [comment] 2019-02-16 20:40
@antiochp do we have some archive folder? I see we keep 32 log files in `~/.grin/main/`, unfortunately grin was producing a new file every 7 mins (now it's 1 in 4-5 hours), so all 32 files are identical and useless.

**Comment by hashmap** [comment] 2019-02-16 20:42
```
ls -alht ~/.grin/main/*.gz
-rw-rw-r-- 1 ubuntu ubuntu 964K Feb 16 17:43 /home/ubuntu/.grin/main/grin-server.log.0.gz
-rw-rw-r-- 1 ubuntu ubuntu 993K Feb 16 13:13 /home/ubuntu/.grin/main/grin-server.log.1.gz
-rw-rw-r-- 1 ubuntu ubuntu 978K Feb 16 06:06 /home/ubuntu/.grin/main/grin-server.log.2.gz
-rw-rw-r-- 1 ubuntu ubuntu 1.1M Feb 16 02:59 /home/ubuntu/.grin/main/grin-server.log.3.gz
-rw-rw-r-- 1 ubuntu ubuntu 552K Feb 15 22:24 /home/ubuntu/.grin/main/grin-server.log.6.gz
-rw-rw-r-- 1 ubuntu ubuntu 571K Feb 15 22:17 /home/ubuntu/.grin/main/grin-server.log.7.gz
-rw-rw-r-- 1 ubuntu ubuntu 559K Feb 15 22:02 /home/ubuntu/.grin/main/grin-server.log.9.gz
-rw-rw-r-- 1 ubuntu ubuntu 570K Feb 15 21:54 /home/ubuntu/.grin/main/grin-server.log.10.gz
-rw-rw-r-- 1 ubuntu ubuntu 575K Feb 15 21:47 /home/ubuntu/.grin/main/grin-server.log.11.gz
-rw-rw-r-- 1 ubuntu ubuntu 557K Feb 15 21:40 /home/ubuntu/.grin/main/grin-server.log.12.gz
-rw-rw-r-- 1 ubuntu ubuntu 543K Feb 15 21:32 /home/ubuntu/.grin/main/grin-server.log.13.gz
-rw-rw-r-- 1 ubuntu ubuntu 557K Feb 15 21:25 /home/ubuntu/.grin/main/grin-server.log.14.gz
-rw-rw-r-- 1 ubuntu ubuntu 553K Feb 15 21:17 /home/ubuntu/.grin/main/grin-server.log.15.gz
-rw-rw-r-- 1 ubuntu ubuntu 548K Feb 15 21:10 /home/ubuntu/.grin/main/grin-server.log.16.gz
-rw-rw-r-- 1 ubuntu ubuntu 532K Feb 15 21:02 /home/ubuntu/.grin/main/grin-server.log.17.gz
-rw-rw-r-- 1 ubuntu ubuntu 542K Feb 15 20:54 /home/ubuntu/.grin/main/grin-server.log.18.gz
-rw-rw-r-- 1 ubuntu ubuntu 548K Feb 15 20:46 /home/ubuntu/.grin/main/grin-server.log.19.gz
-rw-rw-r-- 1 ubuntu ubuntu 570K Feb 15 20:39 /home/ubuntu/.grin/main/grin-server.log.20.gz
-rw-rw-r-- 1 ubuntu ubuntu 538K Feb 15 20:31 /home/ubuntu/.grin/main/grin-server.log.21.gz
-rw-rw-r-- 1 ubuntu ubuntu 540K Feb 15 20:24 /home/ubuntu/.grin/main/grin-server.log.22.gz
-rw-rw-r-- 1 ubuntu ubuntu 547K Feb 15 20:16 /home/ubuntu/.grin/main/grin-server.log.23.gz
-rw-rw-r-- 1 ubuntu ubuntu 553K Feb 15 20:09 /home/ubuntu/.grin/main/grin-server.log.24.gz
-rw-rw-r-- 1 ubuntu ubuntu 562K Feb 15 20:02 /home/ubuntu/.grin/main/grin-server.log.25.gz
-rw-rw-r-- 1 ubuntu ubuntu 529K Feb 15 19:54 /home/ubuntu/.grin/main/grin-server.log.26.gz
-rw-rw-r-- 1 ubuntu ubuntu 523K Feb 15 19:47 /home/ubuntu/.grin/main/grin-server.log.27.gz
-rw-rw-r-- 1 ubuntu ubuntu 536K Feb 15 19:40 /home/ubuntu/.grin/main/grin-server.log.28.gz
-rw-rw-r-- 1 ubuntu ubuntu 577K Feb 15 19:33 /home/ubuntu/.grin/main/grin-server.log.29.gz
-rw-rw-r-- 1 ubuntu ubuntu 580K Feb 15 19:25 /home/ubuntu/.grin/main/grin-server.log.30.gz
-rw-rw-r-- 1 ubuntu ubuntu 576K Feb 15 19:18 /home/ubuntu/.grin/main/grin-server.log.31.gz
```

**Comment by antiochp** [comment] 2019-02-18 10:36
Ahh - I didn't realize we only kept a limited number of recent archived files around.

**Comment by codeb2cc** [comment] 2019-06-17 06:53
It seems I've encountered the same error:

> 20190617 06:41:09.204 DEBUG grin_servers::common::adapters - Received block 0000003dc43f at 214818 from 67.189.14.118:3414 [in/out/kern: 24/14/7] going to process.
20190617 06:41:09.205 DEBUG grin_chain::pipe - pipe: process_block 0000003dc43f at 214818 [in/out/kern: 24/14/7]
20190617 06:41:09.205 DEBUG grin_chain::txhashset::txhashset - Rewind header extension to 000005a95b90 at 214816
20190617 06:41:09.210 DEBUG grin_chain::txhashset::txhashset - Rewind to header 000005a95b90 at 214816
20190617 06:41:09.210 DEBUG grin_chain::txhashset::txhashset - txhashset: rewind_to_pos: header 429626, output 2528257, kernel 1293768
20190617 06:41:09.211 DEBUG grin_chain::txhashset::txhashset - Error returned, discarding txhashset extension: Already Spent: Commitment(09c4939816c93e6591c787e0308cbe607c424abdc6f36f4d0160522f1a0e81795b) 
 Cause: Unknown 
 Backtrace: 
20190617 06:41:09.212 INFO grin_chain::chain - Rejected block 0000003dc43f at 214818: Error { inner: 
Already Spent: Commitment(09c4939816c93e6591c787e0308cbe607c424abdc6f36f4d0160522f1a0e81795b) }
20190617 06:41:09.212 DEBUG grin_servers::common::adapters - process_block: block 0000003dc43f refused by chain: Other Error: Error { inner: 
Already Spent: Commitment(09c4939816c93e6591c787e0308cbe607c424abdc6f36f4d0160522f1a0e81795b) }

And now my node is stuck at 214818.

**Comment by pharazen** [comment] 2019-07-17 18:10
This appears to happen often when a commitment was included in an orphaned block. In @codeb2cc specific case the commitment was included in an orphan at the previous height. In the other examples we can't see the orphans in the explorer, but that may just mean they did not survive long enough to make it to the explorer's node, and where thrown out, but only before corrupting the state of that node's inputs.

Is it possible that orphaned blocks are not having their inputs correctly rolled back to the prior state?

**Comment by chrouzz** [comment] 2019-08-13 03:06
any way to fix it?

**Comment by j01tz** [comment] 2019-08-13 03:38
@chrouzz can you share the software version you are running and any debug output?

**Comment by devilrayzl** [comment] 2019-08-23 12:23
It seemed I met the same problem .
```
20190823 20:17:18.264 DEBUG grin_chain::txhashset::txhashset - Error returned, discarding txhashset extension: Already Spent: Commitment(09b02b43f60bb2275d0cc68c4a8b4bc1c48248860c43db28e4c3658c6b9eade8f3) 
 Cause: Unknown 
 Backtrace: 
20190823 20:17:18.265 INFO grin_chain::chain - Rejected block 0000147bc6bb at 306612: Error { inner: 

Already Spent: Commitment(09b02b43f60bb2275d0cc68c4a8b4bc1c48248860c43db28e4c3658c6b9eade8f3) }
```

How to fix it???Anybody can help??

I'm using `grin 2.0.0`

**Comment by devilrayzl** [comment] 2019-08-23 12:37
Clear chain_data and resync.
This may be one of the solution.

**Comment by quentinlesceller** [comment] 2019-09-05 19:30
Duplicate of https://github.com/mimblewimble/grin/issues/3018. Closing.

**Comment by hashmap** [comment] 2019-09-06 07:50
@quentinlesceller #3018 sounds like a manual workaround for this issue, shouldn't we keep it and fix eventually?

**Closed** 2019-10-21 21:49 UTC
Labels: bug
