### ISSUE TITLE
[Server] thread 'syncer' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin#305] opened 2017-11-18 09:31 UTC
This happened after clearing out the .grin directory and the wallet.dat file, restart of the computer, and initial run of wallet listener and non-mining server (after occurrence of previous issue #304).

16.04.1-Ubuntu SMP x86_64

````
Nov 18 11:16:55.102 DEBG Sync: blocks to download 2100, block downloading 7
Nov 18 11:16:55.103 DEBG Requesting block 3a5f8d5f from peer 109.74.202.16:13414.
Nov 18 11:16:55.103 DEBG Requested 1 full blocks to download, total left: 2099. Current list: [BlockDownload { hash: 1f727461, start_time: Instant { tv_sec: 650, tv_nsec: 366659386 }, retries: 0 }, BlockDownload { hash: c9104299, start_time: Instant { tv_sec: 650, tv_nsec: 366837265 }, retries: 0 }, BlockDownload { hash: 68ddc414, start_time: Instant { tv_sec: 650, tv_nsec: 366980157 }, retries: 0 }, BlockDownload { hash: 9e6adf06, start_time: Instant { tv_sec: 650, tv_nsec: 367125787 }, retries: 0 }, BlockDownload { hash: f94abdab, start_time: Instant { tv_sec: 650, tv_nsec: 367258607 }, retries: 0 }, BlockDownload { hash: ab5efd47, start_time: Instant { tv_sec: 650, tv_nsec: 367375977 }, retries: 0 }, BlockDownload { hash: dfb3c8af, start_time: Instant { tv_sec: 650, tv_nsec: 367506445 }, retries: 0 }, BlockDownload { hash: 3a5f8d5f, start_time: Instant { tv_sec: 652, tv_nsec: 369269109 }, retries: 0 }].
Nov 18 11:16:56.606 INFO Client 109.74.202.16:13414 connection lost: Timeout
Nov 18 11:16:57.103 DEBG Sync: peer 8517334 vs us 8518862
Nov 18 11:16:57.104 DEBG Sync: blocks to download 2099, block downloading 8
Nov 18 11:16:57.104 DEBG Requested 0 full blocks to download, total left: 2099. Current list: [BlockDownload { hash: 1f727461, start_time: Instant { tv_sec: 650, tv_nsec: 366659386 }, retries: 0 }, BlockDownload { hash: c9104299, start_time: Instant { tv_sec: 650, tv_nsec: 366837265 }, retries: 0 }, BlockDownload { hash: 68ddc414, start_time: Instant { tv_sec: 650, tv_nsec: 366980157 }, retries: 0 }, BlockDownload { hash: 9e6adf06, start_time: Instant { tv_sec: 650, tv_nsec: 367125787 }, retries: 0 }, BlockDownload { hash: f94abdab, start_time: Instant { tv_sec: 650, tv_nsec: 367258607 }, retries: 0 }, BlockDownload { hash: ab5efd47, start_time: Instant { tv_sec: 650, tv_nsec: 367375977 }, retries: 0 }, BlockDownload { hash: dfb3c8af, start_time: Instant { tv_sec: 650, tv_nsec: 367506445 }, retries: 0 }, BlockDownload { hash: 3a5f8d5f, start_time: Instant { tv_sec: 652, tv_nsec: 369269109 }, retries: 0 }].
Nov 18 11:16:58.654 DEBG monitoring peers (1)
Nov 18 11:16:58.654 DEBG cleaning V4(109.74.202.16:13414), not connected
Nov 18 11:16:58.655 DEBG Got 50 more peers from db, trying to connect.
thread 'syncer' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Nov 18 11:17:08.654 DEBG monitoring peers (0)
Nov 18 11:17:08.656 DEBG Got 50 more peers from db, trying to connect.
Nov 18 11:17:18.654 DEBG monitoring peers (0)
Nov 18 11:17:18.656 DEBG Got 50 more peers from db, trying to connect.
Nov 18 11:17:28.654 DEBG monitoring peers (0)
Nov 18 11:17:28.656 DEBG Got 50 more peers from db, trying to connect.
Nov 18 11:17:38.654 DEBG monitoring peers (0)
Nov 18 11:17:38.656 DEBG Got 50 more peers from db, trying to connect.
Nov 18 11:17:38.656 DEBG event loop running
Nov 18 11:17:48.238 ERRO Peer request error: Connection(Error { repr: Os { code: 110, message: "Connection timed out" } })
Nov 18 11:17:48.238 DEBG saving peer to store PeerData { addr: V4(185.45.22.93:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Defunct }
Nov 18 11:17:48.239 DEBG New peer address to connect to: 165.227.63.166:13414.
Nov 18 11:17:48.239 DEBG 0.0.0.0:13414 connecting to 165.227.63.166:13414
Nov 18 11:17:48.483 DEBG handshake connect with nonce - 17881271424102495379, sender - V4(0.0.0.0:13414), receiver - V4(165.227.63.166:13414)
Nov 18 11:17:48.654 DEBG monitoring peers (0)
````

Full log at [grin.log.tar.gz](https://github.com/mimblewimble/grin/files/1484471/grin.log.tar.gz)

**Comment by ignopeverell** [comment] 2017-11-18 18:56
Unfortunately I can't see the more details as the panic wasn't captured in the logs. I'm guessing however that it happened because you weren't connected to any peer (which was very likely fixed with the same PRs that fixed #304). I've added a more helpful message on that particular panic as well in addaadf so it's easier to diagnose.

**Closed by ignopeverell** 2017-11-18 18:56 UTC

**Comment by AsrielBelacqua** [comment] 2017-11-22 12:19
I got a similar looking panic when trying to resync today (at commit 69801f332):

```
Nov 22 12:07:54.257 DEBG Sync: Asking peer 91.8.7.95:13414 for more block headers, locator: [520aa3b6, 171ef4d5, d9a4
9edf, 6989e374, 7dbdbbcd, 6a05e671, 733b31bf, cdc9cc05, e4985e32, 5310b551, e17ea64f]
Nov 22 12:07:54.258 DEBG Sync: peer error, will retry
Nov 22 12:07:54.258 DEBG Sync: Retry 6 on block 67d4bac9
thread 'syncer' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
Nov 22 12:07:54.261 DEBG New peer address to connect to: 84.172.93.17:13436.
Nov 22 12:07:54.265 DEBG 0.0.0.0:13414 connecting to 84.172.93.17:13436 
Nov 22 12:07:54.267 DEBG New peer address to connect to: 63.131.221.130:13414.
Nov 22 12:07:54.269 DEBG 0.0.0.0:13414 connecting to 63.131.221.130:13414 
Nov 22 12:07:54.271 DEBG New peer address to connect to: 84.172.93.17:13414.
Nov 22 12:07:54.279 DEBG 0.0.0.0:13414 connecting to 84.172.93.17:13414 
Nov 22 12:07:54.285 DEBG handshake connect with nonce - 15106062141915960293, sender - V4(0.0.0.0:13414), receiver - V4(84.172.94.18:13439) 
Nov 22 12:07:54.382 INFO Connected to peer PeerInfo { capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", version: 1, addr: V4(84.172.94.18:13439), total_difficulty: Difficulty { num: 29745464 } }
Nov 22 12:07:54.382 DEBG Saving newly connected peer 84.172.94.18:13439. 
Nov 22 12:07:54.383 DEBG saving peer to store PeerData { addr: V4(84.172.94.18:13439), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Healthy }
Nov 22 12:07:54.385 DEBG Asking 84.172.94.18:13439 for more peers.
Nov 22 12:07:54.422 DEBG Received 22 peer addrs, saving.
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:32
  11: grin_grin::sync::Syncer::request_block
             at /home/stelmaria/src/grin/grin/src/sync.rs:319
  12: grin_grin::sync::Syncer::request_bodies
             at /home/stelmaria/src/grin/grin/src/sync.rs:202
  13: grin_grin::sync::Syncer::run 
             at /home/stelmaria/src/grin/grin/src/sync.rs:138
  14: grin_grin::adapters::NetToChainAdapter::start_sync::{{closure}} 
             at /home/stelmaria/src/grin/grin/src/adapters.rs:300
```

Sorry not to have a verbose backtrace (will remember to use 'full' next time), and I am not sure if the cause is the same, but here is a log anyway: 
[grin.log](https://github.com/mimblewimble/grin/files/1495905/grin.log)

**Comment by AsrielBelacqua** [comment] 2017-11-22 14:14
Full backtrace:

```
Nov 22 12:24:52.338 DEBG Sync: blocks to download 4054, block downloading 8
Nov 22 12:24:52.338 DEBG Sync: Loc heights: [2371, 2369, 2367, 2363, 2355, 2339, 2307, 2243, 2115, 1859, 0]
Nov 22 12:24:52.339 INFO Client 84.172.94.18:13430 connection lost: Connection(Error { repr: Custom(Custom { kind: Un
expectedEof, error: StringError("early eof") }) })
Nov 22 12:24:52.339 DEBG monitoring peers (1)
Nov 22 12:24:52.339 DEBG cleaning V4(84.172.94.18:13430), not connected
Nov 22 12:24:52.347 DEBG Got 50 peers from db, trying to connect.
Nov 22 12:24:52.350 DEBG event loop running
Nov 22 12:24:52.353 DEBG New peer address to connect to: 96.59.144.27:13414.
Nov 22 12:24:52.361 DEBG 0.0.0.0:13414 connecting to 96.59.144.27:13414
Nov 22 12:24:52.364 DEBG New peer address to connect to: 95.153.132.254:13414.
Nov 22 12:24:52.365 DEBG 0.0.0.0:13414 connecting to 95.153.132.254:13414
Nov 22 12:24:52.368 DEBG New peer address to connect to: 68.2.90.28:13414.
Nov 22 12:24:52.369 DEBG 0.0.0.0:13414 connecting to 68.2.90.28:13414
Nov 22 12:24:52.373 DEBG New peer address to connect to: 84.172.95.182:13414.
Nov 22 12:24:52.375 DEBG 0.0.0.0:13414 connecting to 84.172.95.182:13414
Nov 22 12:24:52.379 DEBG New peer address to connect to: 207.229.182.167:30000.
Nov 22 12:24:52.388 DEBG 0.0.0.0:13414 connecting to 207.229.182.167:30000
Nov 22 12:24:52.391 DEBG New peer address to connect to: 188.64.25.107:13414.
Nov 22 12:24:52.392 DEBG 0.0.0.0:13414 connecting to 188.64.25.107:13414
Nov 22 12:24:52.395 DEBG New peer address to connect to: 12.69.234.140:13414.
Nov 22 12:24:52.396 DEBG 0.0.0.0:13414 connecting to 12.69.234.140:13414
Nov 22 12:24:52.401 DEBG New peer address to connect to: 176.158.47.85:13414.
Nov 22 12:24:52.402 DEBG 0.0.0.0:13414 connecting to 176.158.47.85:13414
Nov 22 12:24:thread '52syncer' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/optio
n.rs:335:.20                                                                                                         725 DEBG Sync: Asking peer 84.172.94.18:13430 for more block headers, locator: [1fa2e60b, 1aadec4c, 0879f478, 50291d3
8, cc4ba00e, c8c0b470, 86c99347, a41f6f93, 6ec0f4c8, 1b0773a6, e17ea64f]                                             Nov 22 12:24:52.725 DEBG Sync: peer error, will retry
Novstack backtrace:
 22 12:24:52.725 DEBG Sync: Retry 3 on block f9396e62
   0:     0x562e38df6363 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hfc7985b08e763a82
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x562e38df2354 - std::sys_common::backtrace::_print::h16a1db02a59ead63
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x562e38df98d3 - std::panicking::default_hook::{{closure}}::h48ecee46f2eefc30
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x562e38df9642 - std::panicking::default_hook::hb4c92ae8d005ca44
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x562e38df9d97 - std::panicking::rust_panic_with_hook::h25d461655d60b1a5
                               at /checkout/src/libstd/panicking.rs:611
   5:     0x562e38df9bf4 - std::panicking::begin_panic::h0f6fdd9abfd7dfb9
                               at /checkout/src/libstd/panicking.rs:572
   6:     0x562e38df9b69 - std::panicking::begin_panic_fmt::ha31e26b280c9e878
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x562e38df9afa - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x562e38e32910 - core::panicking::panic_fmt::h67504914198d0451
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x562e38e32846 - core::panicking::panic::hc8058a23bb7ed97d
                               at /checkout/src/libcore/panicking.rs:51
  10:     0x562e37768542 - <core::option::Option<T>>::unwrap::he56e0d757c003a50
                               at /checkout/src/libcore/macros.rs:32
  11:     0x562e3794fc9b - grin_grin::sync::Syncer::request_block::h04f7fd7974d0167f
                               at /home/stelmaria/src/grin/grin/src/sync.rs:319
  12:     0x562e3794d271 - grin_grin::sync::Syncer::request_bodies::hc11032f798f9c28b
                               at /home/stelmaria/src/grin/grin/src/sync.rs:202
  13:     0x562e3794baac - grin_grin::sync::Syncer::run::hdd6239c83e88aa5b
                               at /home/stelmaria/src/grin/grin/src/sync.rs:138
  14:     0x562e379407ae - grin_grin::adapters::NetToChainAdapter::start_sync::{{closure}}::h9b686d6c6c17353b
                               at /home/stelmaria/src/grin/grin/src/adapters.rs:300
  15:     0x562e3776fdcc - std::sys_common::backtrace::__rust_begin_short_backtrace::h05d9beee3047197e
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  16:     0x562e3778c06c - std::thread::Builder::spawn::{{closure}}::{{closure}}::h92d28f8a817bb343
                               at /checkout/src/libstd/thread/mod.rs:394
  17:     0x562e3771a1bc - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9867e2ea
843656d4
                               at /checkout/src/libstd/panic.rs:296
  18:     0x562e3778d339 - std::panicking::try::do_call::ha9007d265c14488e
                               at /checkout/src/libstd/panicking.rs:480
  19:     0x562e38e00e7c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  20:     0x562e3778c68a - std::panicking::try::h1bbba89ea2b784eb
                               at /checkout/src/libstd/panicking.rs:459
  21:     0x562e37788483 - std::panic::catch_unwind::he24b0607d0ee7bc7
                               at /checkout/src/libstd/panic.rs:361
  22:     0x562e3778bb45 - std::thread::Builder::spawn::{{closure}}::hde0089dd90b757ba
                               at /checkout/src/libstd/thread/mod.rs:393
  23:     0x562e3783972f - <F as alloc::boxed::FnBox<A>>::call_box::h381a24e23a1174de
                               at /checkout/src/liballoc/boxed.rs:682
  24:     0x562e38df8c3b - std::sys::imp::thread::Thread::new::thread_start::hf0e7be833820328e
                               at /checkout/src/liballoc/boxed.rs:692
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  25:     0x7f0b4d2da6b9 - start_thread
  26:     0x7f0b4cdfa3dc - clone
  27:                0x0 - <unknown>
Nov 22 12:24:57.365 DEBG saving peer to store PeerData { addr: V4(96.59.144.27:13414), capabilities: , user_agent: ""
, flags: Defunct }
Nov 22 12:24:57.370 DEBG saving peer to store PeerData { addr: V4(95.153.132.254:13414), capabilities: , user_agent: 
"", flags: Defunct }
Nov 22 12:24:57.373 DEBG saving peer to store PeerData { addr: V4(68.2.90.28:13414), capabilities: , user_agent: "", 
flags: Defunct }
Nov 22 12:24:57.380 DEBG saving peer to store PeerData { addr: V4(84.172.95.182:13414), capabilities: , user_agent: "
", flags: Defunct }
Nov 22 12:24:57.395 DEBG saving peer to store PeerData { addr: V4(207.229.182.167:30000), capabilities: , user_agent:
 "", flags: Defunct }
Nov 22 12:24:57.396 DEBG saving peer to store PeerData { addr: V4(188.64.25.107:13414), capabilities: , user_agent: "
", flags: Defunct }
Nov 22 12:24:57.408 DEBG saving peer to store PeerData { addr: V4(12.69.234.140:13414), capabilities: , user_agent: "
", flags: Defunct }
Nov 22 12:24:57.409 DEBG saving peer to store PeerData { addr: V4(176.158.47.85:13414), capabilities: , user_agent: "
", flags: Defunct }
Nov 22 12:25:02.251 DEBG monitoring peers (0)
Nov 22 12:25:02.257 DEBG Got 50 peers from db, trying to connect.
```

[grin.log](https://github.com/mimblewimble/grin/files/1496241/grin.log)

**Comment by AsrielBelacqua** [comment] 2017-11-22 20:55
Just got this again on commit 75761bc5: http://termbin.com/yxwv (can provide a full log again if necessary)

**Comment by ignopeverell** [comment] 2017-11-22 20:56
Could you have lost internet connection temporarily? This panic shows sync could not find any peer you were connected to, which is confirmed by `monitoring peers(0)` in your logs. In the absence of anyone to connect to, the node can't proceed.

I've added a more explicit error in 861c54c.

**Comment by AsrielBelacqua** [comment] 2017-11-22 21:02
Hmm, how odd. I would be surprised about the loss of internet (running remotely with a VPS, and didn't notice any trouble with SSH), and I don't seem to have 0 peers in the log associated with that last termbin paste (yxwv). Will try re-running with 861c54c.
