### ISSUE TITLE
Node lagging 5 blocks behind

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1924] opened 2018-11-05 08:38 UTC
Observed this several times. I have two nodes. Roughly around 08:14:
- grin1 is at 25983.
- grin2 is at 25987.

However grin1 finally sync:
```
2018-11-05T08:14:47.513517573+00:00 INFO grin_servers::grin::sync::syncer - sync: total_difficulty 1329355826, peer_difficulty 1329525033, threshold 165444 (last 5 blocks), enabling sync
```

This issue lasted 5 minutes in that case. Is there any reason for this behaviour or is it just the expected?
[grin-1.log](https://github.com/mimblewimble/grin/files/2547470/grin-1.log)
[grin-2.log](https://github.com/mimblewimble/grin/files/2547471/grin-2.log)

**Comment by hashmap** [comment] 2018-11-05 09:07
Perhaps duplicate of https://github.com/mimblewimble/grin/issues/1799 we somehow miss one block via gossip

**Comment by antiochp** [comment] 2018-11-05 10:55
Yeah I think I've seen something similar a couple of times recently (testnet4).
We miss a single block (no idea how or why) and the behavior looks like this.

**Comment by antiochp** [comment] 2018-12-02 15:59
Closing for now - getting rid of the block header cache should have removed the underlying issue here.
Lets reopen if we see it reoccur.

**Closed by antiochp** 2018-12-02 15:59 UTC
Labels: duplicate
