### ISSUE TITLE
Grin on native Windows

### ISSUE THREAD

**Issue by jaspervdm** [mimblewimble/grin#2062] opened 2018-12-01 14:41 UTC
Opening this issue to keep track of getting Grin to run on Windows natively. A simple `cargo build` fails when trying to build croaring. There might be additional crates giving issues but I didn't get past the first one.

It might be worth it to try and get just the wallet working on Windows, since that doesn't actually use croaring. It is however needed by other parts of Grin so it is listed as a dependency for `grin_chain`, `grin_core` and `grin_store`, so it will take some effort to try and untangle these.

At the moment this issue is not a priority for the devs, but if anyone else is willing to pick this up they are very much welcome.

**Comment by drizzt** [comment] 2018-12-05 10:52
I'm able to build grin on Windows successfully.
Unfortunately it fails in sync with error:
    Could not write to state storage, disk full? Os { code: 5, kind: PermissionDenied, message: "Access is denied." } }

**Comment by sesam** [comment] 2018-12-05 12:29
What build environment did you use?
Win 10 pro? Below 10 or below pro some features are likely missing / might make it harder to build.
Manually added features? (linux/ubuntu windows subsystem?)
Via cygwin / similar?
cargo/rustc versions and how were they installed?

This is also important to add into the build documentation. I can update the wiki.

**Comment by drizzt** [comment] 2018-12-05 12:31
I cross compiled from Fedora 29 using `cargo build --target x86_64-pc-windows-gnu` (last rustup stable) and tested in on Windows 10 Professional

**Comment by sesam** [comment] 2018-12-05 12:38
the -windows-gnu target probably means the binary uses the cygwin runtime library, which cares about permissions that a normal windows software might not be stopped by. On startup, grin goes into ~/.grin to do stuff.

Maybe try fixing up ownership and permissions on the .grin folder?
`bash -c mkdir ~/.grin; chmod -R 775 ~/.grin; chown -R $USER:$USER ~/.grin`

**Comment by drizzt** [comment] 2018-12-05 15:19
Since building for Windows can be a problem I created a Dockerfile to simplify the process:
https://gist.github.com/drizzt/fa4d62fc1118b387078bc06bd6c69009

**Comment by ignopeverell** [comment] 2018-12-05 17:39
You can play with the LMDB store size and see if that helps. Ultimately we should auto-detect the running environment to set it appropriately. But I expect you'll run in a few other issues after that...

**Comment by ignopeverell** [comment] 2018-12-05 23:02
I think it's an issue with how Windows handles memory mapping. Everything MMR related uses mmap. @yorickdowne previously filed this bug against WSL:

https://github.com/Microsoft/WSL/issues/3451

I understand you're not running against WSL but perhaps similar system calls are used under the hood.

**Comment by drizzt** [comment] 2018-12-06 22:13
This should be another problem since no zero-length mmap is done in store/src/types.rs

**Comment by yeastplume** [comment] 2019-01-22 13:22
Given https://github.com/saulius/croaring-rs/pull/42, is getting Grin working on Windows really that far off? Surely it would seem all that has to happen now is an alternate PMMR backend that doesn't use memmap?

**Comment by yeastplume** [comment] 2019-01-22 14:07
Also confused because memmap crate claims to work and be tested on native windows, both msvc and gnu toolchains. This could just be a matter of tracing down an issue in https://docs.rs/crate/memmap/0.7.0

**Comment by cyberpunkbln** [comment] 2019-01-28 15:50
Hello,

for my understandings, the problem is that mw/grin are an peer2peer application and under windows only a complete compiled wallet can deliver mw/grin functions. Webwallets, Paperwallets, nodejs/javascript and other known applications are not possible?

**Comment by kargakis** [comment] 2019-05-17 19:59
We are releasing Windows binaries now so I suspect this is fixed now?

**Comment by quentinlesceller** [comment] 2019-05-17 20:01
Indeed @kargakis, closing.

**Closed by quentinlesceller** 2019-05-17 20:01 UTC
Labels: enhancement, help wanted

**Comment by cyberpunkbln** [comment] 2019-05-20 23:04
Hello,
can anybody update the build docs in the wiki for windows 10? Can i use an gnu-mingw-toolchain?
thx
