### ISSUE TITLE
Error on block # 229614 and stop sync.

### ISSUE THREAD

**Issue by motopila** [mimblewimble/grin#2923] opened 2019-06-26 13:54 UTC
Nothing foreshadowed trouble and suddenly node (1.1.0) stopped sync.

Log:
`20190626 16:30:33.641 DEBUG grin_p2p::protocol - handle_payload: received block: msg_len: 16630
20190626 16:30:33.642 DEBUG grin_servers::common::adapters - Received block 000000f15303 at 229614 from 39.106.144.10:3414 [in/out/kern: 18/20/11] going to process.
20190626 16:30:33.642 DEBUG grin_chain::pipe - pipe: process_block 000000f15303 at 229614 [in/out/kern: 18/20/11]
20190626 16:30:33.656 DEBUG grin_chain::txhashset::txhashset - Error returned, discarding txhashset extension: Already Spent: Commitment(09c8798176526d4e59e1f1e5ee6f549a278704a7c55b1a0ddbc1a194307637b37a) 
 Cause: Unknown 
 Backtrace: 
20190626 16:30:33.656 INFO grin_chain::chain - Rejected block 000000f15303 at 229614: Error { inner: 

Already Spent: Commitment(09c8798176526d4e59e1f1e5ee6f549a278704a7c55b1a0ddbc1a194307637b37a) }
20190626 16:30:33.656 DEBUG grin_servers::common::adapters - process_block: block 000000f15303 refused by chain: Other Error: Error { inner: 

Already Spent: Commitment(09c8798176526d4e59e1f1e5ee6f549a278704a7c55b1a0ddbc1a194307637b37a) }`

How to fix it ?

**Comment by hashmap** [comment] 2019-07-03 13:07
Duplicate of https://github.com/mimblewimble/grin/issues/2495

**Closed by hashmap** 2019-07-03 13:07 UTC
