### ISSUE TITLE
Segfault if one folder is removed and db is resized

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#2907] opened 2019-06-21 11:43 UTC
as reported by @chisa0a:

> Recently started testing 2.0.0-beta.1 node, wallet, and reference miner. After running the node, setup for the upcoming test hardfork, I got a segfault after deleting my peer directory.
> 
> I ran the node like the following:
>  - fully synced, no problem. 
>  - restarted a few times, again no issue
>  - decided I wanted fresh peers, so did the quick lazy thing, and deleted my peer directory: `~/.grin/floo/chain_data/peer`
> 
> After restarting, I got a segfault with the following backtrace:
> 
> ```
> #0  0x++ in mdb_env_info ()
> No symbol table info available.
> #1  0x++ in lmdb_zero::env::Environment::info ()
> No symbol table info available.
> #2  0x++ in grin_store::lmdb::Store::needs_resize ()
> No symbol table info available.
> #3  0x++ in grin_store::lmdb::Store::batch ()
> No symbol table info available.
> #4  0x++ in grin_p2p::store::PeerStore::update_state ()
> No symbol table info available.
> #5  0x++ in grin_p2p::peers::Peers::update_state ()
> No symbol table info available.
> #6  0x++ in std::sys_common::backtrace::__rust_begin_short_backtrace ()
> No symbol table info available.
> #7  0x++ in std::panicking::try::do_call ()
> No symbol table info available.
> #8  0x++ in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:87
> No locals.
> #9  0x++ in <F as alloc::boxed::FnBox<A>>::call_box ()
> No symbol table info available.
> #10 0x++ in call_once<(),()> () at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/liballoc/boxed.rs:759
> No locals.
> #11 start_thread () at src/libstd/sys_common/thread.rs:14
> No locals.
> #12 thread_start () at src/libstd/sys/unix/thread.rs:81
> No locals.
> #13 0x++ in start_thread () from /usr/lib/libpthread.so.0
> No symbol table info available.
> #14 0x++ in clone () from /usr/lib/libc.so.6
> No symbol table info available.
> ```
> 
> So the bug is coming from LMDB, and likely spawns from an `unsafe` wrapper inside `lmdb_zero::env::Environment::info` not being implemented properly (since there is no `unsafe` in the surrounding Grin code, and `info` is not marked `unsafe` either.

as commented by @hashmap: 

> It seems we don't check if only one folder was removed and try to resize the db.

**Comment by antiochp** [comment] 2019-06-21 11:52
Interesting. I actually delete my `chain_data/peers` dir on a regular basis.
Its a completely separate LMDB database.
Is this just a simple case of us assuming its there and initialized during a resize?

**Comment by chisa0a** [comment] 2019-06-23 07:20
> I actually delete my chain_data/peers dir on a regular basis.

Right, why I thought doing so would be a safe thing to do, but was met with a segfault.

> Is this just a simple case of us assuming its there and initialized during a resize?

Haven't fully dug into the surrounding code in Grin, or the underlying `lmdb-zero` code. Hopefully, this is a simple problem to fix. What's worrying to me is there appears to be an attempted `panic` catch, but instead of just crashing out, memory corruption occurs.

**Comment by hashmap** [comment] 2019-07-03 13:10
Can't reproduce this issue on the current master

**Comment by yeastplume** [comment] 2020-01-21 14:46
We okay to close this in the post-3.0.0 era?

**Comment by quentinlesceller** [comment] 2020-01-21 16:23
Considering @hashmap comment yes.

**Closed by quentinlesceller** 2020-01-21 16:23 UTC
Labels: bug
