### ISSUE TITLE
Panic 'attempt to subtract with overflow' when building tx with large amount of inputs

### ISSUE THREAD

**Issue by jaspervdm** [mimblewimble/grin#1100] opened 2018-05-29 20:19 UTC
I tried creating a transaction with a very large amount of inputs (5000), but I get the following error:
```
May 29 12:57:30.393 DEBG Extending maximum number of outputs. 5000 outputs selected.
May 29 12:57:38.232 DEBG Extending maximum number of outputs. 5000 outputs selected.
May 29 12:57:39.544 ERRO
thread 'main' panicked at 'attempt to subtract with overflow': wallet/src/grinwallet/selection.rs:277stack backtrace:
   0:     0x56023960bf84 - backtrace::backtrace::libunwind::trace::h5820195e11aea42c
                        at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h9f5a7f7c3d9acf78
                        at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/mod.rs:42
   1:     0x560239609bfc - backtrace::capture::Backtrace::new_unresolved::h993011d448440454
                        at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:88
   2:     0x560239609b4e - backtrace::capture::Backtrace::new::hd86b1c76133310b3
                        at /home/desktop/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:63
   3:     0x560239483e6c - grin_util::logger::send_panic_to_log::{{closure}}::h44a7834ee104c0b9
                        at util/src/logger.rs:119
   4:     0x560239901d79 - std::panicking::rust_panic_with_hook::hed3a578f3d672948
                        at libstd/panicking.rs:403
   5:     0x560239901b62 - std::panicking::begin_panic_fmt::h3e8fdd00db89fef8
                        at libstd/panicking.rs:349
   6:     0x560239901a92 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x560239951690 - core::panicking::panic_fmt::h16b501044b4579f2
                        at libcore/panicking.rs:72
   8:     0x5602399515b6 - core::panicking::panic::h554a74a2e013a3f7
                        at libcore/panicking.rs:51
   9:     0x560238876410 - grin_wallet::grinwallet::selection::inputs_and_change::h7a3247eb4319d1c2
                        at wallet/src/grinwallet/selection.rs:277
  10:     0x560238875204 - grin_wallet::grinwallet::selection::select_send_tx::h5fb951cb1b233fc0
                        at wallet/src/grinwallet/selection.rs:245
  11:     0x560238872dcc - grin_wallet::grinwallet::selection::build_send_tx_slate::h43d34f45aebc0f9a
                        at wallet/src/grinwallet/selection.rs:40
  12:     0x560238673eef - grin_wallet::sender::issue_send_tx::h4d206c2da1f63a4c
                        at wallet/src/sender.rs:71
  13:     0x5602381876b4 - grin::wallet_command::hb41f3935cc13c723
                        at src/bin/grin.rs:566
  14:     0x5602381840dd - grin::main::h9f599ca57a8ee770
                        at src/bin/grin.rs:341
  15:     0x560238211b21 - std::rt::lang_start::{{closure}}::h202b78a17ccd20b5
                        at /checkout/src/libstd/rt.rs:74
  16:     0x5602399019f7 - std::rt::lang_start_internal::{{closure}}::h30a15dfbaf2db741
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h84e823ef113bafaa
                        at libstd/panicking.rs:306
  17:     0x56023991536e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  18:     0x5602398fe4a5 - std::panicking::try::h29c76d75c597e452
                        at libstd/panicking.rs:285
                         - std::panic::catch_unwind::h33ca23d1ecc573a8
                        at libstd/panic.rs:361
                         - std::rt::lang_start_internal::h26bd2a105967b459
                        at libstd/rt.rs:58
  19:     0x560238211b01 - std::rt::lang_start::h43cd7e1a2c7cfda5
                        at /checkout/src/libstd/rt.rs:74
  20:     0x56023818868d - main
  21:     0x7f4bb93d23f0 - __libc_start_main
  22:     0x560238168fa9 - _start
  23:                0x0 - <unknown>


Thread 'main' panicked with message:
"attempt to subtract with overflow"
```

Is there a maximum number of inputs that is causing this error? If so, it would be better if the wallet gave an error indicating this.

**Comment by jaspervdm** [comment] 2018-06-01 19:15
I am not sure what changed, but now I consistently get
```
Jun 01 20:57:46.466 DEBG Posting partial transaction to http://127.0.0.1:13415/v1/receive/transaction
Jun 01 20:58:04.570 DEBG Validating final transaction
Jun 01 20:58:10.302 ERRO Tx not sent: Error { inner: Error { inner: 

Bad arguments: Argument error:  }

Node API error }
```

**Comment by yeastplume** [comment] 2018-06-01 19:29
Sorry, the issue is probably the same as before, but I've just been reworking the Error handling a bit in advance of wallet improvements, and it's probably not quite there yet. Will look into this soon as part of the rework.

**Comment by jaspervdm** [comment] 2018-06-01 19:59
Okay, thanks! Is there actually a limit on the number of inputs a tx or a block can have?

**Comment by ignopeverell** [comment] 2018-06-01 22:43
The wallet should just check for the limit in number of transaction inputs in `core::consensus`.

**Comment by yeastplume** [comment] 2018-06-28 11:34
Wallet code is very refactored and reworked now.. although the most stable version is now in T3... going to close this one for now, but would really appreciate if you could test this again and reopen against T3 once it's launched (which shouldn't be so far off now)

**Closed by yeastplume** 2018-06-28 11:34 UTC

**Comment by jaspervdm** [comment] 2018-06-28 17:45
I will definitely perform more tests once testnet3 comes around
