### ISSUE TITLE
Node Stuck in Sync Loop

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1632] opened 2018-10-02 00:34 UTC
Attaching the grin log, no specific error. Running on 4d2cbe6596462e609a528182e57a965ca4d5aa8d.
[grin.log](https://github.com/mimblewimble/grin/files/2436090/grin.log)

**Comment by ignopeverell** [comment] 2018-10-02 01:17
Needs more digging but this looks like we enter body sync properly but fail to request any block.

**Comment by ignopeverell** [comment] 2018-10-02 01:39
Actually, it's more that there's nothing to request because we're not requesting headers either. It looks like your node has very few peers (6 total, only 3 at the head) so you'd likely benefit from cleaning up your peer db regardless.

Would you have logs around when this particular node went out of sync?

**Comment by quentinlesceller** [comment] 2018-10-02 01:59
Going to clean my peers db. Here is the previous 20 minutes
https://pastebin.com/JKMUhCdj

**Comment by garyyu** [comment] 2018-10-02 02:10
Hey, we don't have `peers db` anymore! don't know when and who merged into chain db. So, you have no way to `clean my peers db` 😃 
But I think it's indeed needed a way to clean the peers, either by an independent db, or by a API.

**Comment by garyyu** [comment] 2018-10-02 02:13
>  node has very few peers (6 total, only 3 at the head) 

Perhaps we need adjust the default configuration from `peer_min_preferred_count = 8` to `peer_min_preferred_count = 16`?  btw, I always change it to 16.

**Comment by ignopeverell** [comment] 2018-10-02 02:50
From his logs, he can't even get 8 so increasing it wouldn't help.

```
Oct 01 22:34:34.702 INFO sync: total_difficulty 49733148, peer_difficulty 49735111, threshold 1934 (last 5 blocks), enabling sync
Oct 01 22:34:34.703 DEBG sync: initial transition to HeaderSync. sync_head: e733c350 at 119872, reset to: c22f3857 at 119876
Oct 01 22:34:34.706 DEBG sync_state: sync_status: NoSync -> HeaderSync { current_height: 119876, highest_height: 119881 }
Oct 01 22:34:34.706 DEBG sync: locator heights : [119876, 119874, 119870, 119862, 119846, 119814, 119750, 119622, 119366, 118854, 117830, 115782, 111686, 103494, 87110, 54342, 0]
```

Following which the node quickly catch up to 119881. Then again:

```
Oct 01 22:39:24.710 INFO sync: total_difficulty 49735111, peer_difficulty 49737151, threshold 1963 (last 5 blocks), enabling sync
Oct 01 22:39:26.045 DEBG sync: locator heights': [119881, 119879, 119875, 119867, 119851, 119819, 119755, 119627, 119371, 118859, 117835, 115787, 111691, 103499, 87115, 54347, 0]
Oct 01 22:39:26.050 DEBG sync_state: sync_status: HeaderSync { current_height: 119881, highest_height: 119886 } -> BodySync { current_height: 119881, highest_height: 119886 }
```

And get a lot of what you need:

```
Oct 01 22:39:26.060 DEBG pipe: sync_block_headers: 4 headers from 0dbbc6db at 119882
Oct 01 22:39:26.061 DEBG header head 0dbbc6db @ 119882
Oct 01 22:39:26.062 DEBG sync head 0dbbc6db @ 119882
Oct 01 22:39:26.063 DEBG header head 01b7e191 @ 119883
Oct 01 22:39:26.064 DEBG sync head 01b7e191 @ 119883
Oct 01 22:39:26.065 DEBG header head 0cc6cf43 @ 119884
Oct 01 22:39:26.066 DEBG sync head 0cc6cf43 @ 119884
Oct 01 22:39:26.068 DEBG header head 092b4aaf @ 119885
Oct 01 22:39:26.068 DEBG sync head 092b4aaf @ 119885
Oct 01 22:39:26.071 INFO Received block headers [0b78f616] from 204.48.26.36:13414
Oct 01 22:39:26.071 DEBG pipe: sync_block_headers: 1 headers from 0b78f616 at 119886
Oct 01 22:39:26.073 DEBG header head 0b78f616 @ 119886
Oct 01 22:39:26.073 DEBG sync head 0b78f616 @ 119886
Oct 01 22:39:26.953 DEBG pipe: process_block 07782069 at 119882 with 0 inputs, 1 outputs, 1 kernels
Oct 01 22:39:26.971 DEBG pipe: chain head 07782069 @ 119882
```

But then it stops there and something weird happens: on the next heads log your header head actually jumps back:

```
Oct 01 22:39:27.182 DEBG body_sync: 0/0 blocks received, and no more in 200ms
Oct 01 22:39:27.182 DEBG body_sync: body_head - 07782069, 119882, header_head - 07782069, 119882, sync_head - 0b78f616, 119886
Oct 01 22:39:27.183 DEBG sync_state: sync_status: BodySync { current_height: 119881, highest_height: 119886 } -> BodySync { current_height: 119882, highest_height: 119886 }
```

So there are 2 things that seem wrong:
1. The fact that your header head jumped back.
2. The fact that no new header sync triggered after that

**Comment by garyyu** [comment] 2018-10-02 06:31
Look like we have 2 surprises here:
> 1. The fact that your header head jumped back.

Only possibility here I can imagine is, the new mined block will **wrongly overwrite** the `header_head`:
```
Oct 01 22:39:26.068 DEBG header head 092b4aaf @ 119885
Oct 01 22:39:26.953 DEBG pipe: process_block 07782069 at 119882 with 0 inputs, 1 outputs, 1 kernels
Oct 01 22:39:26.974 WARN (Server ID: StratumServer) Solution Found for block 119882 - Yay!!!
Oct 01 22:39:26.975 INFO (Server ID: StratumServer) Got share for block: hash 07782069, height 119882, nonce 2198979844995478195, difficulty 986/407, submitted by white
Oct 01 22:39:27.182 DEBG body_sync: body_head - 07782069, 119882, header_head - 07782069, 119882, sync_head - 0b78f616, 119886
```

> 2. The fact that no new header sync triggered after that

```
Oct 01 22:39:26.048 DEBG sync: request_headers: asking 204.48.26.36:13414 for headers, [0435de48, 04a627c9, 0ade2460, 0c439e20, 11f2eb25, 0c2f582d, 0878a083, 0aa7cbd3, 117eeafb, 1eab7704, 09e854d0, 0c3c9f9c, 1e9c520d, 12ba3581, 012f27c4, 02292233, 006642e0]
```
and after problem 1 happened, we come to 2nd problem:
```
	fn header_sync_due(&mut self, sync_state: &SyncState, header_head: &chain::Tip) -> bool {
		...
		let stalling = header_head.height == latest_height && now > timeout;
```

because `header_head.height` was updated by problem 1, this `stalling` will then be always `false`.

Sync is our bugs bed :(

**Comment by garyyu** [comment] 2018-10-02 08:17
@antiochp   another `impossible` thing here?

Received 5 Headers and `header_head` updated to `0b78f616 @ 119886`:
```
Oct 01 22:39:26.060 DEBG pipe: sync_block_headers: 4 headers from 0dbbc6db at 119882
Oct 01 22:39:26.061 DEBG header head 0dbbc6db @ 119882
Oct 01 22:39:26.062 DEBG sync head 0dbbc6db @ 119882
Oct 01 22:39:26.063 DEBG header head 01b7e191 @ 119883
Oct 01 22:39:26.064 DEBG sync head 01b7e191 @ 119883
Oct 01 22:39:26.065 DEBG header head 0cc6cf43 @ 119884
Oct 01 22:39:26.066 DEBG sync head 0cc6cf43 @ 119884
Oct 01 22:39:26.068 DEBG header head 092b4aaf @ 119885
Oct 01 22:39:26.068 DEBG sync head 092b4aaf @ 119885
Oct 01 22:39:26.071 INFO Received block headers [0b78f616] from 204.48.26.36:13414
Oct 01 22:39:26.071 DEBG pipe: sync_block_headers: 1 headers from 0b78f616 at 119886
Oct 01 22:39:26.073 DEBG header head 0b78f616 @ 119886
Oct 01 22:39:26.073 DEBG sync head 0b78f616 @ 119886
```

Mined a new block at 119882:
```
Oct 01 22:39:26.953 DEBG pipe: process_block 07782069 at 119882 with 0 inputs, 1 outputs, 1 kernels
Oct 01 22:39:26.971 DEBG pipe: chain head 07782069 @ 119882
        <<<< Note:  no log with "DEBG header head hash @ height",
        <<<< means `update_header_head` return `None` and not updated, because it's not the "most work" chain.

Oct 01 22:39:26.974 WARN (Server ID: StratumServer) Solution Found for block 119882 - Yay!!!
Oct 01 22:39:26.975 INFO (Server ID: StratumServer) Got share for block: hash 07782069, height 119882, nonce 2198979844995478195, difficulty 986/407, submitted by white
Oct 01 22:39:27.182 DEBG body_sync: body_head - 07782069, 119882, header_head - 07782069, 119882, sync_head - 0b78f616, 119886
        <<<< problem here!   the 'header_head' is indeed 119882! impossible!
```

```
fn update_header_head(
	bh: &BlockHeader,
	ctx: &mut BlockContext,
	batch: &mut store::Batch,
) -> Result<Option<Tip>, Error> {
	let tip = Tip::from_block(bh);
	if tip.total_difficulty > ctx.header_head.total_difficulty {
		batch
			.save_header_head(&tip)
			.map_err(|e| ErrorKind::StoreErr(e, "pipe save header head".to_owned()))?;
		ctx.header_head = tip.clone();
		debug!(LOGGER, "header head {} @ {}", bh.hash(), bh.height);
		<<<< if updated, we will see this log!

		Ok(Some(tip))
	} else {
		Ok(None)
	}
}
```

**Comment by antiochp** [comment] 2018-10-02 09:08
So maybe mining for a while on an old block?
Node did not know it was old because we got out of sync.

The `ctx` passed in the `update_header_head` has an old stale `header_head` in it that we incorrectly compare our new total_diff against.

**Comment by garyyu** [comment] 2018-10-02 09:55
@antiochp  no,  If @quentinlesceller is correct, his node is in running on 4d2cbe6, not the latest version.  I'm reading the exact version code of his `4d2cbe6`.

**Comment by antiochp** [comment] 2018-10-02 10:04
I want to take some time and see what happens if we remove our dependency on the `head` and `header_head` in the `ctx`.
We should be able to go back to either the `chain.head()` (which is the one source of truth) or the db (aka the batch aka the active db transaction) for this.

I'm just not clear on how this will impact performance (probably not much given our batch usage) or code complexity.

**Comment by quentinlesceller** [comment] 2018-10-02 14:07
For what it's worth I've experienced the same issue last night on f15bfbd35b2d16d103d331915dc34cd0e70d2f9a.
Attaching another log.
[grin-crash.log](https://github.com/mimblewimble/grin/files/2438191/grin-crash.log)

**Comment by antiochp** [comment] 2018-10-02 14:12
@garyyu my comments were more general - we've always had this issue with the `ctx` getting out of date if we process a block in another thread.
This is not a recently introduced problem (I don't think anyway).

**Comment by ignopeverell** [comment] 2018-10-02 19:58
Taking a few chosen lines from @quentinlesceller new log, same issue of the header head being overwritten:

```
Oct 02 06:59:21.498 DEBG body_sync: body_head - 04553eca, 120369, header_head - 039d25d0, 120375, sync_head - 039d25d0, 120375
Oct 02 06:59:21.499 DEBG block_sync: 120369/120375 requesting blocks [0f54023e, 052778ce, 0c7bd532, 0e45dcb8, 00fd56c0, 0c19ae81, 055effbf, 02743bd8, 0a1ad298, 039d25d0] from 3 peers
Oct 02 06:59:21.584 DEBG pipe: chain head 0eb437d8 @ 120370
Oct 02 06:59:21.853 DEBG body_sync: body_head - 0eb437d8, 120370, header_head - 0eb437d8, 120370, sync_head - 039d25d0, 120375
```

@quentinlesceller I do think you need to do something with the peer list on this node, in that last log you only had 1 most work peer.
@antiochp I agree with the `ctx` observations.

**Comment by quentinlesceller** [comment] 2018-10-02 20:51
@ignopeverell Okay thanks, I'll look for a way to integrate a "reset the peer list" using the node endpoint.

**Comment by ignopeverell** [comment] 2018-10-02 23:34
This outlines a few issues:

1. We shouldn't accept a block from the miner when we're syncing.
2. There's a little loose end in `header_sync_due` when the header head jumps back, `stalling` doesn't become true.
3. For nodes that have been running for a while (like Quentin's), we probably don't fish out defunct nodes or not well enough (thought someone had looked at this before?).

Fixes incoming.

**Comment by garyyu** [comment] 2018-10-03 02:56
> 3. For nodes that have been running for a while (like Quentin's), we probably don't fish out defunct nodes or not well enough (thought someone had looked at this before?).

An old issue in https://github.com/mimblewimble/grin/issues/1586

**Comment by garyyu** [comment] 2018-10-03 03:02
@antiochp 
>  we've always had this issue with the ctx getting out of date if we process a block in another thread.

👍   I suppose **this** is the real root cause?  thanks to address this.

and should we add some test cases to simulate this: `process a block in another thread`?  better for us to quickly find more similar problems.

**Comment by ignopeverell** [comment] 2018-10-03 05:13
@garyyu mmh no, the context change by itself wouldn't prevent this issue. The header head would still be overwritten by a block processed without the `SYNC` option.

**Comment by antiochp** [comment] 2018-10-03 12:33
> There's a little loose end in header_sync_due when the header head jumps back, stalling doesn't become true.

The proposed changes in #1650 should resolve this, making it effectively impossible for `header_head` to jump back due to processing on another thread.

**Comment by ignopeverell** [comment] 2018-10-09 16:48
Hopefully fixed, or at least a similar issue will be different enough to warrant its own issue.

**Closed by ignopeverell** 2018-10-09 16:48 UTC
Labels: bug
