### ISSUE TITLE
body_sync: cannot sync full blocks earlier than horizon

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#1880] opened 2018-10-30 08:41 UTC
```
DEBUG grin_chain::chain - check_orphans: 9 blocks accepted since height 10814, remaining # orphans 7
DEBUG grin_p2p::protocol - handle_payload: received block: msg_len: 1255
DEBUG grin_servers::common::adapters - Received block 0538b707 at 10823 from 54.38.70.127:13414, inputs: 0, outputs: 1, kernels: 1, going to process.
DEBUG grin_chain::pipe - pipe: process_block 0538b707 at 10823 with 0 inputs, 1 outputs, 1 kernels
DEBUG grin_servers::grin::sync::body_sync - body_sync: no pending block request, asking more
DEBUG grin_servers::grin::sync::body_sync - body_sync: body_head - 0610a255, 10822, header_head - 06b88088, 17334, sync_head - 06b88088, 17334
DEBUG grin_servers::grin::sync::body_sync - body_sync: cannot sync full blocks earlier than horizon.
```

Looks like an impossible happening! since header_head at 17334 and body_head at 10822.  horizon is 10080.
https://github.com/mimblewimble/grin/blob/b4ee1e14a435c33c3e1e30c4be7a99a87ba07a0a/servers/src/grin/sync/body_sync.rs#L124-L127

Can't explain how it happened at this moment, let's wait to next happening of this problem.

BTW, then it will enter an infinite loop to report same log:
```
2018-10-30T14:57:38.901211+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: no pending block request, asking more
2018-10-30T14:57:38.901321+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: body_head - 00dbe703, 10828, header_head - 06b88088, 17334, sync_head - 06b88088, 17334
2018-10-30T14:57:38.901371+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: cannot sync full blocks earlier than horizon.
2018-10-30T14:57:38.913408+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: no pending block request, asking more
2018-10-30T14:57:38.913499+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: body_head - 00dbe703, 10828, header_head - 06b88088, 17334, sync_head - 06b88088, 17334
2018-10-30T14:57:38.913556+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: cannot sync full blocks earlier than horizon.
2018-10-30T14:57:38.925944+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: no pending block request, asking more
2018-10-30T14:57:38.926023+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: body_head - 00dbe703, 10828, header_head - 06b88088, 17334, sync_head - 06b88088, 17334
2018-10-30T14:57:38.926062+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: cannot sync full blocks earlier than horizon.
2018-10-30T14:57:38.938313+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: no pending block request, asking more
2018-10-30T14:57:38.938390+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: body_head - 00dbe703, 10828, header_head - 06b88088, 17334, sync_head - 06b88088, 17334
2018-10-30T14:57:38.938447+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: cannot sync full blocks earlier than horizon.
2018-10-30T14:57:38.949738+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: no pending block request, asking more
2018-10-30T14:57:38.949818+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: body_head - 00dbe703, 10828, header_head - 06b88088, 17334, sync_head - 06b88088, 17334
2018-10-30T14:57:38.949860+08:00 DEBUG grin_servers::grin::sync::body_sync - body_sync: cannot sync full blocks earlier than horizon.
...
```

**Comment by hashmap** [comment] 2018-10-30 08:44
duplicate of https://github.com/mimblewimble/grin/issues/1845

**Comment by garyyu** [comment] 2018-10-30 09:09
Ah, thanks @hashmap . Since it already happened in #1845 and it's confused for its impossible, let me add some logs to see the next happening.

**Closed** 2018-12-14 07:04 UTC
Labels: bug, duplicate
