### ISSUE TITLE
Weird symbols instead of interface lines and buttons

### ISSUE THREAD

**Issue by mbajam** [mimblewimble/grin#2983] opened 2019-07-30 19:42 UTC
**Describe the bug**
Weird symbols appear instead of lines and columns, buttons dissapeared too. Use builded version cause release just not do, possibly because of processor model etc.

**Screenshots**
![1](https://user-images.githubusercontent.com/34043732/62159622-d4124700-b31a-11e9-94a2-36209586d53a.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [18.04 LTS]

**Comment by jaspervdm** [comment] 2019-07-31 09:53
Duplicate of https://github.com/mimblewimble/grin/issues/2429

**Closed** 2019-07-31 11:07 UTC
