### ISSUE TITLE
Wallet restore producing incorrect amounts

### ISSUE THREAD

**Issue by andybellenie** [mimblewimble/grin#355] opened 2017-11-21 12:54 UTC
Doing wallet restore on a freshly synced seed is giving me an incorrect value of 1639.968 grin

Seed is `af58b5d9bf6b1f388ecc2bb5a2120396eb7c77c98fbc5767d35ea18d4f03cb5b`

Frustratingly I deleted the original wallet.dat but this node had only mined 400 plus a few test transactions.

**Comment by yeastplume** [comment] 2017-11-21 12:57
Hi Andy.. please see my comments on https://github.com/mimblewimble/grin/issues/354 (I'm going to close this as a duplicate of that one.

**Closed by yeastplume** 2017-11-21 12:57 UTC
