### ISSUE TITLE
Thread Panic beta 2: Illegal instruction

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#2827] opened 2019-05-15 18:18 UTC
**Describe the bug**
Panic when running beta 2 (from binary) for the first time.

**Relevant Information**
Logs: https://gist.github.com/lehnberg/f6d9971b49d0ea8ae73860662f427364
I wasn't running a backtrace at the time unfortunately.

**Screenshots**
![screenshot](https://i.ibb.co/dj8b9LX/Screenshot-2019-05-15-at-18-59-02.png)

**Desktop (please complete the following information):**
 macOS v10.14.4

**Comment by ignopeverell** [comment] 2019-05-15 18:26
Your node looks like it was synced already ("Running")?

**Comment by lehnberg** [comment] 2019-05-15 18:38
Right haha - Updated it.

**Comment by lehnberg** [comment] 2019-05-15 18:39
@bladedoyle that's strange tho, as I was running on a MacBook Pro, which supports avx2 iirc.

**Comment by quentinlesceller** [comment] 2019-05-15 20:23
FTR I just synced from scratch using latest binary on macOS.

**Comment by bladedoyle** [comment] 2019-05-15 20:45
@lehnberg There very well be other causes.   I just wanted to share my experience in case it helped.

**Comment by leopheard** [comment] 2019-06-02 00:46
Also having this issue running on an Ubuntu 18 laptop and the system info is telling me the CPU is an Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz.

Error log here (same 'illegal instruction' error):

[https://pastebin.com/meJ65A6Z](url)

**Comment by hashmap** [comment] 2019-07-03 14:24
Duplicate of https://github.com/mimblewimble/grin/issues/2494

**Closed by hashmap** 2019-07-03 14:24 UTC
Labels: bug
