### ISSUE TITLE
High chance to miss a header if a node has not many peers

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#2732] opened 2019-04-04 20:18 UTC
My NAT'd node is behind its peers the most of the time. 

First of all it can't get enough peers and often the number is below `peer_min_preffered_count` (will investigate). Also connections are dropped pretty often, average life time is ~ 30 seconds.

Node broadcasts a new header to `peer_min_preffered_count` number of peers, so if this value is low and number of peers is high chances to get the header from this particular node are pretty low. If we multiply it by number of peers we are often way below 1. Also if we got connected to a node after it broadcasted the header we are out of luck, keep in mind that reconnection rate is high so it's not a rare event.

As result my node doesn't receive headers pretty often, so it consider or subsequent headers as orphans and it has to rely on header sync only.

```
20190404 11:34:26.885 DEBUG grin_servers::sync::header_sync - sync: initial transition to HeaderSync. sync_head: 000005478a5a at 112896, resetting to: 000005478a5a at 112896
20190404 11:41:34.160 DEBUG grin_servers::sync::header_sync - sync: initial transition to HeaderSync. sync_head: 000016b858d1 at 112902, resetting to: 0000021b0acd at 112903
20190404 11:49:00.942 DEBUG grin_servers::sync::header_sync - sync: initial transition to HeaderSync. sync_head: 00001035cccf at 112909, resetting to: 00001035cccf at 112909
```

**Comment by DavidBurkett** [comment] 2019-04-04 21:02
One thing Grin++ does to offset some of the issues caused by the peer connection problems we have is if a peer sends a header with a higher difficulty, it 
also requests the previous compact block from the peer if we don't already have it. That way if you miss a block, you don't have to wait for syncing logic to kick in.

**Comment by hashmap** [comment] 2019-04-04 21:13
@DavidBurkett we have a similar logic for blocks, but not for headers

**Comment by DavidBurkett** [comment] 2019-04-04 21:31
Seems strange that we would have it for blocks and not headers, considering we use header-first propagation.

**Comment by antiochp** [comment] 2019-04-05 15:02
> One thing Grin++ does to offset some of the issues caused by the peer connection problems we have is if a peer sends a header with a higher difficulty, it
also requests the previous compact block from the peer if we don't already have it. That way if you miss a block, you don't have to wait for syncing logic to kick in.

Is there a threshold here where this would not happen?
Say I'm at height 0 (a new node just starting up) and a peer sends me a header at height 100,000.
We used to do something like this in Grin and ended up removing it as it would end up causing a node to slowly sync blocks in reverse order.

I'm guessing - 
* you see a higher _header_
* so you ask for the previous _compact_block_ (not the previous _header_)

So it only resolves a gap of 1?

**Comment by DavidBurkett** [comment] 2019-04-05 15:24
> so you ask for the previous compact_block (not the previous header)

That's correct, and I mentioned that in the quoted text.

> So it only resolves a gap of 1?

It's a recursive solution. So it can technically resolve any gap (that isn't resolved by syncing).

> We used to have something in Grin that did it on missing blocks by asking for blocks - and it would cause a node to sync in reverse order (slowly) back from chain head to genesis.

It only occurs when not syncing.

**Comment by hashmap** [comment] 2019-04-05 21:43
I think it makes sense to apply to headers the same logic we have for blocks. We can have a threshold to start this recursive procedure - eg only if we 10 or less blocks behind (and perhaps if we see 2+ peers on the same height). 

There are 2 problems when we miss just one block - node is useless for next 1-10 minutes and after that we need a pretty expensive chain rebuild (see the image, sync thread is selected)
<img width="1277" alt="Screenshot 2019-04-04 at 15 11 20" src="https://user-images.githubusercontent.com/417244/55657907-1d82d780-57fc-11e9-90f7-d4c4288c0150.png">

**Closed** 2019-07-03 14:27 UTC
