### ISSUE TITLE
thread 'peer' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: 

### ISSUE THREAD

**Issue by hendi** [mimblewimble/grin#2461] opened 2019-01-23 21:25 UTC
Seeing this happen plenty of times lately:

```20190123 22:24:00.999 ERROR grin_util::logger - 
thread 'peer' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: 

Store Error: chain head }': libcore/result.rs:1009stack backtrace:
   0:     0x5652d0a424dd - backtrace::backtrace::trace::hd74837959dc31a2c
   1:     0x5652d0a416f2 - <backtrace::capture::Backtrace as core::default::Default>::default::hfbe03539066da14f
   2:     0x5652d0a41769 - backtrace::capture::Backtrace::new::hd9d47426559d8b68
   3:     0x5652d09ccfb0 - grin_util::logger::send_panic_to_log::{{closure}}::h6b81febaf2dee014
   4:     0x5652d0b13456 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x5652d0b12fa1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x5652d0b12e85 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x5652d0b5cefc - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x5652d0446cc9 - core::result::unwrap_failed::h3b758a2195466880
   9:     0x5652d045fef8 - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::total_difficulty::h0ea2a42447c8b8ca
  10:     0x5652d08bc4ce - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::hbf375e138c1a9d12
  11:     0x5652d08cadea - std::sys_common::backtrace::__rust_begin_short_backtrace::h420154df4fe05d1a
  12:     0x5652d08aebc4 - std::panicking::try::do_call::he46ff5ccacde053d
  13:     0x5652d0b254f9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  14:     0x5652d08aac9c - <F as alloc::boxed::FnBox<A>>::call_box::h6cae2131db46ab93
  15:     0x5652d0b0f9dd - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  16:     0x5652d0afad55 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  17:     0x7f6f3e1a0493 - start_thread
  18:     0x7f6f3dccbace - __clone
  19:                0x0 - <unknown>
```

**Comment by hashmap** [comment] 2019-01-24 09:37
I experience the same, looks like a db issue when node has a lot of peers (~ 150 in my case), will investigate

**Comment by hashmap** [comment] 2019-01-24 09:45
Duplicate of #2388, closing

**Closed by hashmap** 2019-01-24 09:45 UTC
Labels: bug
