### ISSUE TITLE
cpu_miner causes Segmentation fault: 11

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#964] opened 2018-04-16 12:49 UTC
runnning grin with mining off works fine, but with mining on, the server crashes within several minutes.
setting tui false and RUST_BACKTRACE=1 provides no further clues.

**Comment by andybellenie** [comment] 2018-05-15 12:09
I'm seeing this issue running the standalone miner in mean_compat_cpu mode on a Macbook Pro 2012

**Comment by andybellenie** [comment] 2018-05-15 12:10
Duplicate of https://github.com/mimblewimble/grin-miner/issues/2

**Comment by quentinlesceller** [comment] 2018-06-01 19:31
Can we close this now that the miner is on a separate project ?

**Comment by ignopeverell** [comment] 2018-06-01 21:29
I say yes :-)

**Closed by ignopeverell** 2018-06-01 21:29 UTC
