### ISSUE TITLE
BorrowError on `header_received`

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin#1551] opened 2018-09-19 00:50 UTC
Multiple `BorrowError`s occurred when trying to process a new block header, resulting in my node not processing that block. It then fell out far enough to start sync, which triggered #1524.

```
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
   0:     0x563c3b559fbc - backtrace::backtrace::trace::h802abb1eb78e0eed
   1:     0x563c3b559d72 - <backtrace::capture::Backtrace as core::default::Default>::default::hf307ae8df96e50cf
   2:     0x563c3b559de8 - backtrace::capture::Backtrace::new::h76e7aaf5ebd7a453
   3:     0x563c3b4f4dcf - grin_util::logger::send_panic_to_log::{{closure}}::h97e1cd71910fd2f9
   4:     0x563c3b662c73 - std::panicking::rust_panic_with_hook::hba05450791beb933
                        at libstd/panicking.rs:479
   5:     0x563c3b662819 - std::panicking::continue_panic_fmt::hd2a4220d2e2291e2
                        at libstd/panicking.rs:390
   6:     0x563c3b662715 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x563c3b6bdb8b - core::panicking::panic_fmt::h2c383e888dce42c0
                        at libcore/panicking.rs:77
   8:     0x563c3b10d795 - core::result::unwrap_failed::hbe0edcd4423696ba
   9:     0x563c3b17918a - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::header_received::he3e2896540a63ae4
  10:     0x563c3b3ad47b - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::header_received::he87decbe59a644ff
  11:     0x563c3b3b8fee - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::header_received::h5ae1b5991a84c62e
  12:     0x563c3b3e2d13 - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::hfc5cb2b0b30cdcb7
  13:     0x563c3b3c2546 - std::sys_common::backtrace::__rust_begin_short_backtrace::h42ccb37c1e69be98
  14:     0x563c3b3c3cc8 - std::panicking::try::do_call::hba67bcf4d45cb2b9
  15:     0x563c3b6870f9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  16:     0x563c3b3afc3d - <F as alloc::boxed::FnBox<A>>::call_box::he371d241a133c3e9
  17:     0x563c3b66520a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h940efee7335c8f36
                        at /checkout/src/liballoc/boxed.rs:652
                         - std::sys_common::thread::start_thread::hac18b9ed82bd359d
                        at libstd/sys_common/thread.rs:24
  18:     0x563c3b663185 - std::sys::unix::thread::Thread::new::thread_start::ha15fdd35f58285a3
                        at libstd/sys/unix/thread.rs:90
  19:     0x7fee9b86c6da - start_thread
  20:     0x7fee9b37d88e - __clone
  21:                0x0 - <unknown>
```

**Comment by ignopeverell** [comment] 2018-09-19 19:28
Did some analysis on this error but still scratching my head. Here are a few observations:

* The crash occurs by unwrapping a `BorrowError` in `header_received`.
* `header_received` never unwraps what could be a `BorrowError`. Fine, this is a release build, the compiler inlines stuff.
* As far as I can tell, `BorrowError` can only be returned by a `RefCell` mutable borrow.
* The only place we ever have one of those anywhere `NetToChainAdapter` can reach is in a `OneTime` which the `wo` helper touches.
* But `OneTime` only ever borrows mutably in `init`, which is called during startup, and never thereafter. This error was recorded after hours of runtime.

:confused:

**Comment by hashmap** [comment] 2018-09-19 21:31
We had it before https://github.com/mimblewimble/grin/issues/1144  and I can confirm your observations, it seems to be because of `OneTime` but it looks impossible after startup.

**Comment by garyyu** [comment] 2018-09-20 08:12
What test can trigger this panic? mining?  why I never saw it on the running node.

**Comment by ignopeverell** [comment] 2018-09-20 16:37
@garyyu it occurs fairly rarely. And this particular node wasn't mining. I think it's triggered by a very specific combination of concurrent events in handling blocks and headers. Once it occurs, it seems to happen multiple times for a bit (30 secs to a min) and then disappears again. It's a bugnicorn.

**Comment by garyyu** [comment] 2018-09-23 08:11
Mark here: I also see this error today.

**Comment by garyyu** [comment] 2018-09-23 12:50
Mark: happened again.
```
Sep 23 19:50:24.358 ERRO
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
...
Sep 23 19:56:26.317 ERRO
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
...
   9:        0x10a3c1cbb - grin_servers::common::adapters::NetToChainAdapter::request_block_by_hash::hb7f1103625ae288a
  10:        0x10a3c0cfd - grin_servers::common::adapters::NetToChainAdapter::process_block::h92d67b254249bbaf
  11:        0x10a3bc3c1 - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::hf3d254d990dd5260
  12:        0x10a6886ba - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::compact_block_received::h748640e1aa9c7226
  13:        0x10a673252 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::h3a98b96324c748e1
  14:        0x10a677f2c - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::h3ef031888646b1ee
...
Sep 23 20:04:16.823 ERRO
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
...
   9:        0x10a3c1cbb - grin_servers::common::adapters::NetToChainAdapter::request_block_by_hash::hb7f1103625ae288a
  10:        0x10a3c0cfd - grin_servers::common::adapters::NetToChainAdapter::process_block::h92d67b254249bbaf
  11:        0x10a3bc3c1 - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::hf3d254d990dd5260
  12:        0x10a6886ba - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::compact_block_received::h748640e1aa9c7226
  13:        0x10a673252 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::h3a98b96324c748e1
  14:        0x10a677f2c - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::h3ef031888646b1ee
...
Sep 23 20:09:57.706 ERRO
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
...
   9:        0x10a3c1cbb - grin_servers::common::adapters::NetToChainAdapter::request_block_by_hash::hb7f1103625ae288a
  10:        0x10a3c0cfd - grin_servers::common::adapters::NetToChainAdapter::process_block::h92d67b254249bbaf
  11:        0x10a3bc3c1 - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::hf3d254d990dd5260
  12:        0x10a6886ba - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::compact_block_received::h748640e1aa9c7226
  13:        0x10a673252 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::h3a98b96324c748e1
  14:        0x10a677f2c - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::h3ef031888646b1ee
...
```

will try to use debug version to test, hope to get more usefully backtrace by debug version.

**Comment by garyyu** [comment] 2018-09-23 14:52
The more readable backtrace on debug mode:
```
Sep 23 21:42:39.471 ERRO
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
   0:        0x104b5e814 - backtrace::backtrace::trace::h82eb823bdd666e6f
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x104b5975c - backtrace::capture::Backtrace::new_unresolved::h1572ddbcdcb8a4c9
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x104b596be - backtrace::capture::Backtrace::new::hd858d1b781edfd7f
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x104a42c39 - grin_util::logger::send_panic_to_log::{{closure}}::hcaf134fb9c003263
                        at util/src/logger.rs:121
   4:        0x104ff7ea8 - std::panicking::rust_panic_with_hook::h28749c6c929f49fc
                        at libstd/panicking.rs:479
   5:        0x104ff79fc - std::panicking::continue_panic_fmt::h2b83096170ce8c01
                        at libstd/panicking.rs:390
   6:        0x104ff78e8 - _rust_begin_unwind
                        at libstd/panicking.rs:325
   7:        0x10503a7e1 - core::panicking::panic_fmt::h014200104cad7730
                        at libcore/panicking.rs:77
   8:        0x104391a2b - core::result::unwrap_failed::h63526b7935da81a4
                        at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9:        0x103f3c976 - <core::result::Result<T, E>>::expect::hafe762e2e03aa9b7
                        at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:809
  10:        0x103fa0638 - <core::cell::RefCell<T>>::borrow::h698db23bca7686c6
                        at /Users/travis/build/rust-lang/rust/src/libcore/cell.rs:804
  11:        0x103f69c74 - <grin_util::OneTime<T>>::borrow::hc66b2238fcc7d211
                        at /Users/garyyu/develop/projects/github.com/mimblewimble/grin/util/src/lib.rs:109
  12:        0x103fb3534 - grin_servers::common::adapters::wo::h09bdf6c31d0e479e
                        at servers/src/common/adapters.rs:46
  13:        0x103fb3af5 - grin_servers::common::adapters::NetToChainAdapter::send_block_request_to_peer::h3d3ed1a47b0ba6be
                        at servers/src/common/adapters.rs:589
  14:        0x103fc338c - grin_servers::common::adapters::NetToChainAdapter::request_compact_block::ha50dfc5c689f6144
                        at servers/src/common/adapters.rs:578
  15:        0x103fbe9f8 - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::header_received::hf690bcfe53a22f14
                        at servers/src/common/adapters.rs:248
  16:        0x10467a984 - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::header_received::hae2c09f4497d712e
                        at p2p/src/peers.rs:542
  17:        0x10465a338 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::header_received::hf262d71bfb1621f9
                        at p2p/src/peer.rs:416
  18:        0x1045d9704 - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::h8fd930ac54479417
                        at p2p/src/protocol.rs:169
  19:        0x104609c49 - grin_p2p::conn::poll::{{closure}}::h5cba5262949e70b8
                        at p2p/src/conn.rs:221

```

**Comment by garyyu** [comment] 2018-09-24 03:55
Not easy to fully understand the problem happened~ Just try to do it step by step.

1. Panic location:
```
impl<T> OneTime<T> {
	...
	pub fn borrow(&self) -> Ref<T> {
		Ref::map(self.inner.borrow(), |o| o.as_ref().unwrap())
		            <<<< panic at this borrow()
	}
```

2. `peers` definition:
```
pub struct Peers {
	...
	peers: RwLock<HashMap<SocketAddr, Arc<RwLock<Peer>>>>,
```

3. `peers` definition and initialization in `Server` of `p2p/src/serv.rs`:

```
pub struct Server {
	...
	pub peers: Arc<Peers>,
	...
}
...
impl Server {
	...
	pub fn new(...) {
		...
		Ok(Server {
			...
			peers: Arc::new(Peers::new(PeerStore::new(db_env)?, adapter, config)),
			...
	}
```
4. `peers` initialization in `Server` of `servers/src/grin/server.rs`:
```
pub struct Server {
	...
	pub p2p: Arc<p2p::Server>,
	...
	pub chain: Arc<chain::Chain>,
	...
}

impl Server {
	pub fn start<F>(...)
	{
		...
		let serv = Arc::new(Server::new(config)?);
		...
	}

	pub fn new(mut config: ServerConfig) -> Result<Server, Error> {
		...
		let chain_adapter = Arc::new(ChainToPoolAndNetAdapter::new(...)
		...
		let shared_chain = Arc::new(chain::Chain::init(
			...
			chain_adapter.clone(),
			...
		)?);
		...
		let net_adapter = Arc::new(NetToChainAdapter::new(
			...
			Arc::downgrade(&shared_chain),
			...
		));
		...
		let p2p_server = Arc::new(p2p::Server::new(
			...
			net_adapter.clone(),
			...
		)?);
		chain_adapter.init(Arc::downgrade(&p2p_server.peers));
		pool_net_adapter.init(Arc::downgrade(&p2p_server.peers));
		net_adapter.init(Arc::downgrade(&p2p_server.peers));
				>>>> the key point is these 3 init() function !
		...
		warn!(LOGGER, "Grin server started.");
		Ok(Server {
			...
			p2p: p2p_server,
			chain: shared_chain,
			...
		})
	}
```
The key point is:  we created 3 weak pointer to the value of `p2p_server.peers`, by 3 `init()` functions, which have same code (in 3 different `adapter`: `ChainToPoolAndNetAdapter`, `PoolToNetAdapter`, and `NetToChainAdapter`):
```
	pub fn init(&self, peers: Weak<p2p::Peers>) {
		self.peers.init(peers);
	}
```

```
impl<T> OneTime<T> {
	...
	pub fn init(&self, value: T) {
		let mut inner_mut = self.inner.borrow_mut();
		*inner_mut = Some(value);
	}
```

5. `peers` definition in each `xAdapter`:
```
pub struct NetToChainAdapter {
	...
	peers: OneTime<Weak<p2p::Peers>>,
	...
}

pub struct ChainToPoolAndNetAdapter {
	...
	peers: OneTime<Weak<p2p::Peers>>,
}

pub struct PoolToNetAdapter {
	peers: OneTime<Weak<p2p::Peers>>,
}
```

6. **Analysis**
Looks like the root cause is here: 

- `p2p_server` hold an Arc copy of `Peers` object, which is directly used in thread `connect_and_monitor`.
- the 3 `xAdapter` hold 3 weak pointers to the value of `p2p_server.peers`, and will `borrow()` the weak pointer in 3 different threads. That's the root cause for this random panic of `BorrowError`.
- I'm still not sure whether or not a simple fix solution will work: to use `clone` before getting the `Weak pointer`:
```
		chain_adapter.init(Arc::downgrade(&p2p_server.peers.clone()));
		pool_net_adapter.init(Arc::downgrade(&p2p_server.peers.clone()));
		net_adapter.init(Arc::downgrade(&p2p_server.peers.clone()));
```

will continue later.

**Comment by garyyu** [comment] 2018-09-24 07:00
Unfortunately, above fix solution doesn't work.

After running 3 hours tests with this 'fix', this problem still happen.
```
Sep 24 14:43:23.505 ERRO handle_payload: BanReason BanReason { ban_reason: BadBlockHeader }
Sep 24 14:43:23.510 DEBG Client 104.209.194.130:13414 connection lost: Connection(Custom { kind: ConnectionAborted, error: StringError("read_exact") })
Sep 24 14:43:24.741 ERRO
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
   0:        0x107c897e4 - backtrace::backtrace::trace::h82eb823bdd666e6f
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x107c8472c - backtrace::capture::Backtrace::new_unresolved::h1572ddbcdcb8a4c9
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x107c8468e - backtrace::capture::Backtrace::new::hd858d1b781edfd7f
                        at /Users/garyyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x107b6dc09 - grin_util::logger::send_panic_to_log::{{closure}}::hcaf134fb9c003263
                        at util/src/logger.rs:121
   4:        0x108122e78 - std::panicking::rust_panic_with_hook::h28749c6c929f49fc
                        at libstd/panicking.rs:479
   5:        0x1081229cc - std::panicking::continue_panic_fmt::h2b83096170ce8c01
                        at libstd/panicking.rs:390
   6:        0x1081228b8 - _rust_begin_unwind
                        at libstd/panicking.rs:325
   7:        0x1081657b1 - core::panicking::panic_fmt::h014200104cad7730
                        at libcore/panicking.rs:77
   8:        0x1074bc9fb - core::result::unwrap_failed::h63526b7935da81a4
                        at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9:        0x107067856 - <core::result::Result<T, E>>::expect::hafe762e2e03aa9b7
                        at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:809
  10:        0x1070cb608 - <core::cell::RefCell<T>>::borrow::h698db23bca7686c6
                        at /Users/travis/build/rust-lang/rust/src/libcore/cell.rs:804
  11:        0x107094b54 - <grin_util::OneTime<T>>::borrow::hc66b2238fcc7d211
                        at /Users/garyyu/develop/projects/github.com/mimblewimble/grin/util/src/lib.rs:109
  12:        0x1070de504 - grin_servers::common::adapters::wo::h09bdf6c31d0e479e
                        at servers/src/common/adapters.rs:46
  13:        0x1070deac5 - grin_servers::common::adapters::NetToChainAdapter::send_block_request_to_peer::h3d3ed1a47b0ba6be
                        at servers/src/common/adapters.rs:589
  14:        0x1070ee35c - grin_servers::common::adapters::NetToChainAdapter::request_compact_block::ha50dfc5c689f6144
                        at servers/src/common/adapters.rs:578
  15:        0x1070e99c8 - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::header_received::hf690bcfe53a22f14
                        at servers/src/common/adapters.rs:248
  16:        0x1077a5954 - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::header_received::hae2c09f4497d712e
                        at p2p/src/peers.rs:542
  17:        0x107785308 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::header_received::hf262d71bfb1621f9
                        at p2p/src/peer.rs:416
  18:        0x1077046d4 - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::h8fd930ac54479417
                        at p2p/src/protocol.rs:169
  19:        0x107734c19 - grin_p2p::conn::poll::{{closure}}::h5cba5262949e70b8
                        at p2p/src/conn.rs:221
```

Perhaps it's because I'm doing a bad idea to add `clone() into `.init(Arc::downgrade(&p2p_server.peers.clone()))` ?   since nobody hold the cloned Arc and it will be released immediately after function `Server::new()` returned.

```
impl Server {
	pub fn start<F>(...)
	{
		...
		let serv = Arc::new(Server::new(config)?);
		...
	}
```

**Comment by garyyu** [comment] 2018-09-24 07:11
@ignopeverell  need your help on this 😄 

I read the comments but not sure I understand:
> All adapters use `Weak` references instead of `Arc` to avoid cycles that can never be destroyed. 

Did you see the real `cycles` if not using `Weak` references?

```
// All adapters use `Weak` references instead of `Arc` to avoid cycles that
// can never be destroyed. These 2 functions are simple helpers to reduce the
// boilerplate of dealing with `Weak`.
fn w<T>(weak: &Weak<T>) -> Arc<T> {
	weak.upgrade().unwrap()
}

fn wo<T>(weak_one: &OneTime<Weak<T>>) -> Arc<T> {
	w(weak_one.borrow().deref())
}
```

**Comment by garyyu** [comment] 2018-09-24 07:51
Understand now why this `Weak` is needed, `Peers` also contains `Adapter`, this is the typical `Circular reference`.
```
pub struct Peers {
	pub adapter: Arc<ChainAdapter>,
	...
}
```

**Comment by garyyu** [comment] 2018-09-24 11:02
Try saving the cloned copy into the `Server`.
After a few hours tests, the problem still happen, **now I'm totally lost and no more idea on this! Could anybody help?**  I will switch to other tasks.

```
		// Save the cloned copy of these 'peers.clone' into Server.
		// Just for avoiding auto-released after this 'new()' function return.
		let mut peers_clones = vec![];
		{
			for _ in 0..3 {
				peers_clones.push(p2p_server.peers.clone());
			}
			chain_adapter.init(Arc::downgrade(&peers_clones[0]));
			pool_net_adapter.init(Arc::downgrade(&peers_clones[1]));
			net_adapter.init(Arc::downgrade(&peers_clones[2]));
		}
		...
		Ok(Server {
			...
			peers_clones,
			...
```

```
pub struct Server {
	...
	peers_clones: Vec<Arc<p2p::Peers>>,
	...
```

And test result:
```
$ grep panicked grin-server.log
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
```

**Comment by garyyu** [comment] 2018-09-25 04:04
> hashmap @hashmap Sep 24 23:17
@garyyu would you mind to test my branch borrow-error (my repo is https://github.com/yourowncrypto/grin.git)? I replaced panic with error, so it should not kill a peer thread, interesting to see what will happen. Still zero panics on my box, it’s my Moby Dick.

I reproduced and log attached here.
[borrow-error.log](https://github.com/mimblewimble/grin/files/2413705/borrow-error.log)

```
$ grep -n borrow borrow-error.log 
896:Sep 25 11:22:14.393 ERRO Failed to borrow OneTime content: already mutably borrowed
899:Sep 25 11:22:14.486 ERRO Failed to borrow OneTime content: already mutably borrowed
902:Sep 25 11:22:14.524 ERRO Failed to borrow OneTime content: already mutably borrowed
909:Sep 25 11:22:14.573 ERRO Failed to borrow OneTime content: already mutably borrowed
913:Sep 25 11:22:14.613 ERRO Failed to borrow OneTime content: already mutably borrowed
997:Sep 25 11:27:28.003 ERRO Failed to borrow OneTime content: already mutably borrowed
...

$ grep -c borrow borrow-error.log 
35
```

**Comment by hashmap** [comment] 2018-09-25 12:29
As I said I don't see how we can mutably borrow a `OneTime` ref after starting the server, I checked many times and I'm sure we do it only once. However, I found an interesting implementation detail of `RefCell` which is as `OneTime` underlying data structure. It uses one counter for both types of borrows - positive number of immutable refs or -1 for mutable ref. So overflow will be considered as mutable borrowing
https://github.com/rust-lang/rust/blob/master/src/libcore/cell.rs#L1084
Unfortunately it means we somehow got more than 9223372036854775807 active refs to `peers` struct, which is unlikely

**Comment by garyyu** [comment] 2018-09-25 14:12
> As I said I don't see how we can mutably borrow a OneTime ref after starting the server, I checked many times and I'm sure we do it only once. 

IMO, it's the multithread access issue. Please look https://github.com/mimblewimble/grin/issues/1551#issuecomment-423872331

At `6 Analysis`:
> the 3 xAdapter hold 3 weak pointers to the same value of p2p_server.peers, and will borrow() the weak pointer in 3 different threads.

**Comment by hashmap** [comment] 2018-09-25 15:05
It's immutable ref, it can be shared without any issues, 3 immutable refs can't produce one mutable, though ILT 9223372036854775807 + 1 can:)

**Closed** 2018-10-13 00:34 UTC
Labels: bug, help wanted
