### ISSUE TITLE
thread 'unnamed' crash with "should never happen" (mining without a wallet.dat)

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#1011] opened 2018-04-27 02:59 UTC
https://gitter.im/grin_community/Lobby?at=5ae236bb1130fe3d361e76f4
thread 'unnamed' panicked at 'should never happen': wallet/src/receiver.rs:332

-[ ] replace "should never happen" with user-readable explanation
-[ ] name the 'unnamed' thread (there are many nameless ones, but the one we hit here is probably more user-facing than some others)
-[ ] maybe handle missing `wallet.dat` same as if it's there but empty + output a WARNING level hint about the issue and info on how to run restore if the user thinks the wallet.dat shouldn't be empty

**Comment by photis** [comment] 2018-04-27 05:02
Thanks for filing this issue. The error occurs also *when not mining* per se, but just having the server node with stratum enabled ('enable_stratum_server = true' in grin.toml). I noticed before that running a default server node (meaning: with the default grin.toml), *without a grin miner* talking to that node, the log file shows a continuous stream of `acquiring wallet lock` and `released wallet lock` one immediately after the other.

I would hesitate to go along with the 3rd suggestion. Remember we need a way to restore a wallet and therefore we *should* be able to run a grin server *without* a wallet.dat file. It's just that the stratum server should *not* expect there to be a wallet unless there is a *real* need to acquire a lock on the wallet, as in "oops, i got a valid block, I need to put some coinbase in the wallet". So, in the (hopefully rare) cases that we need to restore the wallet, it should be sufficient not to run grin-miner, but just grin server.

**Comment by yeastplume** [comment] 2018-04-27 08:34
Could you put together exact steps to reproduce this please? I've tested a couple of iterations, and I can't find anything wrong.

Wallet locks are needed before any mining can occur, and not just when you find a valid block... you actually need to create a potential coinbase transaction in your wallet before you can attempt to mine a block. 

The stratum server locks and unlocks the wallet to create a block when a new block is needed, (even if there are no clients connected) as it needs to be ready with the latest block when a client does connect. So if stratum is running, it's going to be accessing the wallet file.

**Comment by photis** [comment] 2018-04-27 11:28
> Wallet locks are needed before any mining can occur, and not just when you find a valid block... you actually need to create a potential coinbase transaction in your wallet before you can attempt to mine a block.

Ah! I see, didn't realise that. Maybe a command-line switch to turn off the stratum server would be handy? O.t.o.h. we hopefully don't need to run `wallet restore` that often and its rare use merits going into grin.toml to disable the stratum server.

To reproduce: off the top of my head (I will try to run this and give a full narrative later when my server has finished re-sync'ing)
1. Launch grin with default grin.toml
2. Launch `grin wallet restore`
3. Observe message that wallet.dat must be deleted for the restore to function
4. Delete wallet.dat
5. Observe grin crashing with the aforementioned message

**Comment by yeastplume** [comment] 2018-04-27 12:11
there's an option in grin.toml that turns stratum on and off:
```
enable_stratum_server = false
```

What you're saying for reproduction steps makes sense.. you're deleting a wallet.dat file right out from underneath stratum as it's running.. something one really shouldn't do but definitely could be handled better

**Comment by photis** [comment] 2018-04-27 18:44
Yes, I mentioned that in my first comment above.

**Comment by ignopeverell** [comment] 2018-05-13 17:49
So what do we do with this? Better error when `wallet.dat` can't be read? Close?

**Comment by photis** [comment] 2018-05-13 18:40
The issue that needs to be solved imho is that `grin wallet restore` tells the user to remove the wallet.dat file. At the same time, for `grin wallet restore` to run, there must be a server running, which, since the re-factoring of grin in separate (stratum) server and miner, requires a wallet.dat file **_in its default configuration_**. A simple straight-forward solution could be to change the message that `grin wallet restore` emits in case it finds a wallet.dat file, to include instructions to 
- edit the grin.toml file to `enable_stratum_server = false`
- stop/restart grin
- delete wallet.dat
- run `grin wallet restore`
- edit the grin.toml file to `enable_stratum_server = true`
- stop/restart grin

Alternatively we could have command line flag to enable/disable the stratum server (saves editing grin.toml). In any case, the message from `grin wallet restore` that wallet.dat needs to be removed has to change.

**Comment by yeastplume** [comment] 2018-06-28 11:15
Nobody should be attempting to restore into a wallet that's being used by another process.. going to make this clear in the documentation and close this for now

**Closed by yeastplume** 2018-06-28 11:15 UTC
