### ISSUE TITLE
Mainnet fails on Ubuntu 16.04 "grin" 1.0 with default settings.

### ISSUE THREAD

**Issue by damntoken** [mimblewimble/grin#2397] opened 2019-01-16 16:56 UTC
Linux finder 4.4.0-141-generic #167-Ubuntu

running grin...
"Illegal instruction"

 cat ../.grin/main/grin-server.log
20190116 19:04:12.201 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug
20190116 19:04:12.201 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20190116 19:04:12.201 INFO grin - This is Grin version 1.0.0 (git v1.0.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
20190116 19:04:12.201 DEBUG grin - Built with profile "release", features "".
20190116 19:04:12.201 WARN grin::cmd::server - Starting GRIN in UI mode...
20190116 19:04:12.201 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27

After that.. running grin crashes with no output.. log has errors

cat .grin/main/grin-server.log
20190116 18:52:16.615 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug
20190116 18:52:16.615 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20190116 18:52:16.615 INFO grin - This is Grin version 1.0.0 (git v1.0.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
20190116 18:52:16.615 DEBUG grin - Built with profile "release", features "".
20190116 18:52:16.615 WARN grin::cmd::server - Starting GRIN in UI mode...
20190116 18:52:16.615 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190116 18:52:27.336 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug
20190116 18:52:27.336 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20190116 18:52:27.336 INFO grin - This is Grin version 1.0.0 (git v1.0.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
20190116 18:52:27.336 DEBUG grin - Built with profile "release", features "".
20190116 18:52:27.336 WARN grin::cmd::server - Starting GRIN in UI mode...
20190116 18:52:27.336 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190116 18:52:27.353 DEBUG grin_chain::txhashset::txhashset - Error returned, discarding txhashset extension: Other Error: output vs rproof MMRs different sizes
 Cause: Unknown
 Backtrace:
20190116 18:52:27.365 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner:

Other Error: output vs rproof MMRs different sizes })': libcore/result.rs:1009stack backtrace:
   0:     0x55b5b624279d - backtrace::backtrace::trace::hd74837959dc31a2c
   1:     0x55b5b62419b2 - <backtrace::capture::Backtrace as core::default::Default>::default::hfbe03539066da14f
   2:     0x55b5b6241a29 - backtrace::capture::Backtrace::new::hd9d47426559d8b68
   3:     0x55b5b61cb630 - grin_util::logger::send_panic_to_log::{{closure}}::h6b81febaf2dee014
   4:     0x55b5b6313226 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x55b5b6312d71 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x55b5b6312c55 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55b5b635cccc - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x55b5b5a9c419 - core::result::unwrap_failed::h830a8bfc4a83e400
   9:     0x55b5b5a383b0 - grin::cmd::server::start_server::h865872809e516a65
  10:     0x55b5b5a39068 - grin::cmd::server::server_command::hc789d325932205ed
  11:     0x55b5b5ac89fc - grin::real_main::h7464ec6aee075aa9
  12:     0x55b5b5ac6ee5 - grin::main::h76cf7ec850a9936e
  13:     0x55b5b5a951d2 - std::rt::lang_start::{{closure}}::hd67b3eb73f2382c8
  14:     0x55b5b6312bf2 - std::rt::lang_start_internal::{{closure}}::hafa8ecdacd368ebb
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h8c0dbb48abbdf4df
                        at libstd/panicking.rs:310
  15:     0x55b5b63252c9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  16:     0x55b5b62f444a - std::panicking::try::hbc21637ba5f64d73
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h954917b922b8d970
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::h5b2de3cc38c3b406
                        at libstd/rt.rs:58
  17:     0x55b5b5ac9364 - main
  18:     0x7f64fdb5b82f - __libc_start_main
  19:     0x55b5b5a0b980 - <unknown>
  20:                0x0 - <unknown>

PS: oh floonet older release has same bug on that machine, Ill try reinstall.. beacause older release is fine on a VM.

PS PS: so it's still broken after Ubuntu overinstall.. works on laptop CPU, but with Intel(R) Pentium(R) CPU G4560T @ 2.90GHz same buggy symptoms. grin 1.0 AND 0.5.2

**Comment by ignopeverell** [comment] 2019-01-16 18:39
Duplicate of #2334

**Closed by ignopeverell** 2019-01-16 18:39 UTC
