### ISSUE TITLE
[wallet] panic: 'attempt to subtract with overflow' when sending small quantities

### ISSUE THREAD

**Issue by AsrielBelacqua** [mimblewimble/grin#396] opened 2017-11-29 00:17 UTC
wallet listener log: http://termbin.com/zmmi

I was trying to send a tiny quantity (1e-8 grins). Wallet send output:

```
Nov 29 00:17:07.655 INFO Using configuration file at: /home/stelmaria/src/grin/target/debug/grin.toml
Nov 29 00:17:07.660 DEBG Using wallet seed file at: ./wallet.seed
Nov 29 00:17:07.892 DEBG Refreshing wallet outputs
Nov 29 00:17:09.668 INFO Acquiring wallet lock ...
Nov 29 00:17:09.670 DEBG Attempting to acquire wallet lock
Nov 29 00:17:09.834 INFO ... released wallet lock
Nov 29 00:17:09.974 INFO Acquiring wallet lock ...
Nov 29 00:17:09.974 DEBG Attempting to acquire wallet lock
Nov 29 00:17:10.155 INFO ... released wallet lock
Nov 29 00:17:14.198 DEBG Posting partial transaction to http://127.0.0.1:13415/v1/receive/transaction
Nov 29 00:17:14.236 ERRO Error sending transaction - status: 500 Internal Server Error
Nov 29 00:17:14.237 ERRO Communication with receiver failed. Aborting transaction
Nov 29 00:17:14.237 INFO Acquiring wallet lock ...
Nov 29 00:17:14.237 DEBG Attempting to acquire wallet lock
Nov 29 00:17:14.351 INFO cleaning up unused change output from wallet
Nov 29 00:17:14.391 INFO ... released wallet lock
Nov 29 00:17:14.392 ERRO Tx not sent: Hyper(Status)
```

**Comment by antiochp** [comment] 2017-11-29 21:49
Hmm - probably related to the fact we are (incorrectly) building the tx as "receiver pays the fee" when we should be "sender pays the fee" (related #274).
So we're likely trying to subtract a fee thats larger the total amount being sent.

**Comment by mably** [comment] 2017-12-18 15:35
I might have been hit by the same bug: https://hastebin.com/yujufatozu.rb

I was trying to list my wallet outputs, the process crashed.

**Comment by heunglee** [comment] 2018-01-10 08:29
The receiver tries to subtract fee from amount and the result becomes negative and overflow takes place. The problem is that fee is more than the amount. It is not matter of who subtracts fee.
It is necessary to review fee policy for micro grin transfers, such as adjustment of weight of fee for micro grin transfers.

[test case]
I sent 0.00000001 grin coin.
So from the receiver part, the amount was 10, and  the fee was 1000000 grin coin.

thread '<unnamed>' panicked at 'attempt to subtract with overflow', wallet/src/receiver.rs:

fn receive_transaction
     	let out_amount = amount - fee;

For reference, the function to calculate fee is:

const DEFAULT_BASE_FEE: u64 = consensus::MILLI_GRIN;

/// Transaction fee calculation
pub fn tx_fee(input_len: usize, output_len: usize, base_fee: Option<u64>) -> u64 {
	let use_base_fee = match base_fee {
		Some(bf) => bf,
		None => DEFAULT_BASE_FEE,
	};
	let mut tx_weight = -1 * (input_len as i32) + 4 * (output_len as i32) + 1;
	if tx_weight < 1 {
		tx_weight = 1;
	}

	(tx_weight as u64) * use_base_fee
}

**Comment by heunglee** [comment] 2018-01-11 20:20
Until the issue https://github.com/mimblewimble/grin/issues/274 and how to do with amount less than fee w.r.t business requirement finalized, I propose a solution for this issue. When it receives amount less than calculated transaction fee, the receiver sends back error, such as "Error::MoreFeeThanAmount"???

**Comment by ignopeverell** [comment] 2018-01-11 22:07
Yes, an explicit error would already be a lot better.

**Comment by quentinlesceller** [comment] 2018-06-01 19:36
Fixed by https://github.com/mimblewimble/grin/pull/694.

**Closed by quentinlesceller** 2018-06-01 19:36 UTC
Labels: bug, easy, help wanted
