### ISSUE TITLE
On difficulty adjustment

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin#889] opened 2018-03-27 16:41 UTC
It's interesting to compare our Difficulty Adjustment (DA) with that of ZCash [1] and Bitcoin Cash [2].

Coin | ZCash | Grin |  BCash
---- | ----- | ----- | ------
Blocktime in seconds | 150 | 60 | 600
Adjustment Window | 17 | 60 | 144
Median TS Window | 11 | 11 | 3
DAMP_FACTOR | 4 | 3 | 1
AvgDifforTarget | Target | Diff | Diff
Difficulty & TimeSpan | async | async | sync
Minimum TimeSpan | 84% | 50% | 50%
Maximum TimeSpan | 132% | 200% | 200%

Considering that dampening is a mild complication, do we have evidence that it performs
noticeably better than not dampening?

In Zcash, the TS window can be shifted back as much as 10 blocks relative to the Difficulty window of 17 blocks. In Grin's case, this is somewhat less of a problem with the longer window of 60 blocks, but could be further reduced by shortening the median window.

BCash first picks the median timestamps, and then picks the blocks between them.

[1] page 42 of https://github.com/zcash/zips/blob/master/protocol/protocol.pdf
[2] https://medium.com/@Mengerian/dgenr8s-difficulty-adjustment-algorithm-explained-e77aa47eb281

**Comment by zawy12** [comment] 2018-04-30 17:32
BCH uses the median of 3 to determine the front and back of its N=144 window subtraction.  It only protects against bad timestamps if they are 1 out of 3. It comes at a cost of 1 block delay in responding all the time, but with N=144 it doesn't make a difference.  It's 12 hours behind the avg difficulty anyway.  

The 6 block delay in using the MTP, combined with some on-off mining that it encourages, is probably the source of Zcash's slight oscillations.  The 6-block offset between timestamps and difficulty probably does not seem to make a difference (difficulty is so much more stable than timestamps), but it could be a source of the oscillation.   

There is no reason for the 6-block delay.  If it's removed, a bad timestamp will affect only the following block.  If your FTL (future time limit) is reasonable, it's not much of an effect.  It will lower difficulty (N-FTL)/N where FTL is expressed as a multiple of your T (target solvetime) and N is an SMA-equivalent, i.e. 4x17 in Zcash and 3x60 in Grin.   The next honest timestamp completely erases its effect.  A greater than 50% miner will "own the MTP" anyway, so using the median of 3 on front and back works just as good, except for miners in the 33% to 50% range.  And it might work better if the median of 11 is not being checked on the tail end of the Zcash/Grin window

The min and max timespan method is not good.  That's why Zcash took 500 blocks to get to the correct difficulty at startup.  If Zcash were made a faster-responding algorithm, those limits are a time bomb waiting to surprise a future developer. They limit rises and falls to 0.5% when you need difficulty to rise 16%. This gotcha caused me to mess up BTC Gold's algorithm. Other than startup, they are never activated, which is why they have not caused other problems for Zcash.  Limits are not a good idea because the data does not lie unless there has been a catastrophic failure. I have not see the reasoning for them.  To function as expected, they need to be applied to nextTarget or nextDifficulty, not the timespan. Zcash's method of doing it is not quite symmetrical, even if the rise and fall percentages were the same.  1/(1-x) and 1/(1+x) is not the same as 1/(1+x) and 1\*(1+x).

The avgTarget method is better for SMA's and every other algo, but I could not detect that in made a difference in Grin/Zcash type tempering.  SMA's with only difficulty data in the algo can use harmonic mean of difficulty which is equivalent to 1/avgTarget.  avg(1/x) != 1/avg(x).

On a time basis, Grin and Zcash response speeds are about the same due to the different N, tempering, and solvetimes (60/17 x 3/4 x 60/150 = 1.06).  But grin has a stability advantage.  By having a faster solvetime, it gets 2.5x more data points per real time.  If Zcash's stability was sufficient, it should have used N=17\*(150/60)^0.3 = 42 to be 60/42  = 43% faster. Neither comes down fast enough in small-coin hash attacks.

I found Zcash's 4x method be good.  Higher or lower did not seem better. Defintely better than SMAs I used to promote.

So if someday Grin wants to improve it (if it's not reacting fast enough), remove the 6 block delay and change to N=42.

If Grin were small, I'd recommend my LWMA that 30 Monero clones have gone to to completely stop ASIC problems after Monero changed POW, not to mention the previous Nicehash problems.  I'm under agreement with miners to not say that unless I also say POW change can also stop ASIC problems, if not Nicehash.  They need POW change and their dedication to a coin (holding it) is good, as well as marketing and diversity. They love LWMA, but they have to have that POW change.

**Comment by zawy12** [comment] 2018-04-30 18:48
I mean the question is is there a problem? Are there more delays in the should be after big miners leave.? Is it accidentally varying too much so that it's attracting minors? Is it not responding fast enough to price changes? If you send me the last 10 to 50 thousand timestamps in difficulties I can check these things. I expected to be better than zcash because it is able to gather more data points and has the same speed of response. The only change that will have a universally better effect is to either switch the entire algorithm 2 linear weighted moving average of the solve time or remove the MTP delay. Any other change is going to have an offset in one of the other things that you would want. For example if you make it faster it's not going to have as much stability and therefore accidentally attract mining or discourage mining when the price didn't change.

**Comment by zawy12** [comment] 2018-05-26 16:11
If grin has an API i can get timestamps and difficulty data from, I can add it to my "difficulty watch" page:

http://75.190.33.188:6923/

**Comment by ignopeverell** [comment] 2018-05-27 23:29
All nodes have a fairly simple JSON/HTTP API. Is that what you're looking for?

**Comment by zawy12** [comment] 2018-05-28 00:02
I don't want to have to run a node locally for all 30 to 100 coins I list. But I'll eventually try to list all coins using something like digishield, even if i have to run a node.

**Comment by zawy12** [comment] 2018-05-28 14:34
I included it in my list. I changed the address to http://wordsgalore.com/diff 

You don't have difficulty with less than 1, or total difficulty just round up?  There's no way to get difficulty difficulty or target  in the API?  The charts show 1.8 when difficulty was 2 because all charts are  normalized to 1.

**Comment by ignopeverell** [comment] 2018-05-28 18:05
That's pretty nice. It's unlikely to be particularly interesting with testnet2, but I think we should do some more calls to get real miners to try wider fluctuations under testnet3. And yes, min difficulty is 1.

**Comment by zawy12** [comment] 2018-05-30 13:45
The data is indicating something is wrong with your difficulty algorithm.  The past 24 hours avg ST=54 seconds verses target of T=150 seconds, so the D should have been 3x higher than the average.  The average D was 1.35, so it should have averaged about 4, but never went above 2. It seems unlikely the round off error could have caused this.

**Comment by quentinlesceller** [comment] 2018-05-30 13:55
@zawy12 If you are using 198.245.50.26 please note that the node forked on his own chain in the past 24 hours. Fix should arrive soon.

**Comment by tromp** [comment] 2018-05-30 13:57
dear @zawy12,

> The data is indicating something is wrong with your difficulty algorithm.
> The past 24 hours avg ST=54 seconds verses target of T=150 seconds, so the D

Grin has a target block interval of T = 60 seconds.
Do you have Grin confused with Zcash?

regards,
-John

**Comment by zawy12** [comment] 2018-07-26 09:22
**Adjusting current algo**

Summary of the following: I recommend N=25 and timespan limits 4x and 1/4 instead of 2x and 1/2. This is safe in the sense that no additional testing is needed because they are variable changes (any problems in testing would be either an error in testing or an error in the current algorithm).

In the above I've calculated and rationalized that the current N=60 settings for grin should make it about like Zcash.  But it does not need to be so smooth..  It will suffer to some extent from not being faster.  Zcash is not fast enough With the faster T=60, Grin has the freedom to go faster without ill effect. Due to a different damp, an equivalent N to Zcash is about 23.  This is what I would set a small coin to.  I would not go over 40 for Grin.  Also, I would at least make the upper and lower timespan limits 4x and 1/4 instead of 2x and 1/2.   I can't think of a reason to include these limits because the algos calculate correctly. Every time I've seen those limits triggered when they were smaller, it only caused a problem.  I still get people emailing me from problems caused by 4x and 1/4 although I don't expect that problem here.    I've moved the limits down in LWMA to perform more predictably on next_difficulty instead of the timespan. The limits are set to where the LWMA should never reach them unless the code is in error or a timestamp or other unforeseen hack has occurred.

**If switching to LWMA**
Zelcash is the first Zcash clone to switch to my LWMA difficulty algorithm.  It went from being in the upper 25% of "worst performance" to to the upper 25% "best performing".  Here's a visual view of the improvement in a Zcash issue:
https://github.com/zcash/zcash/issues/3244#issuecomment-407393866

There is now LWMA-2, but it is new, so if Grin moves to LWMA (I realize it probably will not due to cost/ benefit ratio at this late time), it needs to remove the "2" part of LWMA-2.  BTW it is now done in integer math. The N for T=60 should be 90.  (this is about 2.5x faster than grin's current setting.

**Comment by ignopeverell** [comment] 2018-08-02 16:29
As you mention the cost/benefit of switching to LWMA doesn't seem to make that much sense at this point, but the adjustments you mention seem reasonable to me. Thank you for still looking into our difficulty adjustment algo.

@tromp @yeastplume any objection? Of course we'll have to see what to do for T3.

**Comment by zawy12** [comment] 2018-08-02 20:26
I changed my 2nd paragraph to be more clear about the justification in going from N=60 to N=30. eally, I think it needs to be N=25 so that it looks more like Zcash in block time.   Or change the 3 to a 4 and use N=17 to be just like Zcash... but keep the 1/2 and 2x or go to 1/4 and 4x instead of Zcash's 16% and 32% which causes start up to take 500 blocks to get to the right target.  With 1/2 and 2x it might take 150 blocks.  If your your initial difficulty is closer, say ~100x off instead of 10,000x , then maybe it can get on track in less than 100 blocks.

**Comment by tromp** [comment] 2018-08-02 21:37
> Adjusting current algo
>
> Summary of the following: I recommend N=25 and timespan limits 4x and 1/4
> instead of 2x and 1/2. This is safe in the sense that no additional testing
> is needed because they are variable changes (any problems in testing would
> be either an error in testing or an error in the current algorithm).
>
> In the above I've calculated and rationalized that the current N=60 settings
> for grin should make it about like Zcash. But it does not need to be so
> smooth.. It will suffer to some extent from not being faster. Zcash is not
> fast enough With the faster T=60, Grin has the freedom to go faster without
> ill effect. Due to a different damp, an equivalent N to Zcash is about 23.
> This is what I would set a small coin to. I would not go over 40 for Grin.
> Also, I would at least make the upper and lower timespan limits 4x and 1/4
> instead of 2x and 1/2. I can't think of a reason to include these limits
> because the algos calculate correctly. Every time I've seen those limits
> triggered when they were smaller, it only caused a problem. I still get
> people emailing me from problems caused by 4x and 1/4 although I don't
> expect that problem here. I've moved the limits down in LWMA to perform more
> predictably on next_difficulty instead of the timespan. The limits are set
> to where the LWMA should never reach them unless the code is in error or a
> timestamp or other unforeseen hack has occurred.

> @tromp @yeastplume any objection?

I pushed for the increase of N to 60 as I see smaller values giving
too much room for timestamp manipulation.
If you want to go faster, I'd rather reduce the dampening from 3 to 2.
Btw, the dampening renders our lower timespan of 1/2 meaningless since
dampening already raises a 0 timespan back up to 2/3. In other words,
dampening itself gives an implicit lower timespan of (dampfactor - 1)
/ dampfactor. So in that sense reducing dampening factor to 2 better
corresponds to our currently ineffective lower timespan.

What problems do you see with lowering the dampening factor?

regards,
-John

**Comment by zawy12** [comment] 2018-08-03 00:17
Lowering it will make it closer to SMA, which does not perform nearly as well as a damp of 4.  In my tests, it seemed like the 4 dampening was the best. Below 3 started to become clearly not as optimal. Also going much above 4 did not seem good.  The damp method is really good at being smoother for a given speed of response in going up.  It's not as good as a similar LWMA in coming back down after the hash rate drops, which was my deciding factor.

I forgot that Grin might be retaining BTC's 7200 future time limit, which would greatly assist a bad timestamp attack.  What is it set to?  The amount it can lower difficulty at least once every damp\*N blocks is something like
```D drop from bad timestamp = 1- N*damp/(N*damp + FTL/T)```
T=60, FTL = 7200, N=60, and damp =60 
=> 40% drop

The above assumes the MTP is not the most recent block, but I believe you are using the MTP, so the attacker has to have > 50% in order to "own the MTP" by getting 6 of the past 11 blocks in order to get the bad timestamp through. Another gotcha, is that if he succeeds, then his bad timestamps will make the difficulty rise as they pass out the back of the window, setting the difficulty up for a fall in the future when he can return. 

If you have the same future time limit (FTL) that nodes will approve as Zcash, then N=25 should OK, unless you are aware that Zcash had timestamp manipulation problems. I'm not sure if they kept the BTC limit of 7200 which I said before genesis should be lowered to about 1800 which would keep it at 12xT since that's what BTC had.  In Cryptonote coins when they switched to my faster (lower N) LWMA, we switched from the 7200 default to 3xT.....360 seconds for T=120 coins.  So far none of the 50 or so set like this have reported a problem from such a short window.

That's interesting that the lower 1/2 limit can't be activated.

**Comment by zawy12** [comment] 2018-08-03 07:54
FTL in BTC-like clones is found according to my instructions for LWMA:
```
//  FTL must be changed to 300 or N*T/20 whichever is higher.
//  FTL in BTC clones is MAX_FUTURE_BLOCK_TIME in chain.h.
//  FTL in Ignition, Numus, and others can be found in main.h as DRIFT.
//  FTL in Zcash & Dash clones need to change the 2*60*60 here:
//  if (block.GetBlockTime() > nAdjustedTime + 2 * 60 * 60)
// which is around line 3450 in main.cpp in ZEC and validation.cpp in Dash
```
To be clear, this setting is important.  It affects Grin more than Zcash because the T is lower, so the FTL/T is higher which means the difficulty can be dropped more.

**Comment by tromp** [comment] 2018-08-03 08:30
On Fri, Aug 3, 2018 at 9:54 AM, zawy12 <notifications@github.com> wrote:
> FTL in BTC-like clones is found according to my instructions for LWMA:
>
> //  FTL must be changed to 300 or N*T/20 whichever is higher.
> //  FTL in BTC clones is MAX_FUTURE_BLOCK_TIME in chain.h.
> //  FTL in Ignition, Numus, and others can be found in main.h as DRIFT.
> //  FTL in Zcash & Dash clones need to change the 2*60*60 here:
> //  if (block.GetBlockTime() > nAdjustedTime + 2 * 60 * 60)
> // which is around line 3450 in main.cpp in ZEC and validation.cpp in Dash
>
> To be clear, this setting is important. It affects Grin more than Zcash
> because the T is lower, so the FTL/T is higher which means the difficulty
> can be dropped more.

Grin has (in chain/src/core/pipe.rs)

if header.timestamp
222 > Utc::now() + Duration::seconds(12 * (consensus::BLOCK_TIME_SEC as i64)

so that's 12 * (T=60) = 720, which is N*T/5.

I don't know where the 12 comes from. It should not be hard to limit
clock drift to 5 minutes
(your 300), so I'd be fine with changing it from 12 to 5.

regards,
-John

**Comment by tromp** [comment] 2018-08-03 09:49
On Fri, Aug 3, 2018 at 2:18 AM, zawy12 <notifications@github.com> wrote:
> Lowering it will make it closer to SMA, which does not perform nearly as
> well as a damp of 4. In my tests, it seemed like the 4 dampening was the
> best. Below 3 started to become clearly not as optimal. Also going much
> above 4 did not seem good. The damp method is really good at being smoother
> for a given speed of response in going up.

Ok; then we'll keep the dampening factor at 3.
I don't mind changing the min & max adjust to 1/4 and 4x,
but I really like a retargeting window of exactly an hour.

-John

**Comment by zawy12** [comment] 2018-08-03 10:15
If you make FTL 360, then you could lower N=25 and max D drop would be 7.5%.  I think a drop of 10% is OK.  N=60 verses N=25 is a very complicated decision.  If the coin is going to be the largest for the given POW, then N=60.  Otherwise I'm for N=25 because it's a lot like Zcash in block time and that's the 2nd best algo being used all the way from Zcash down to small coins.  My previous comments saying N=60 is like Zcash is only about real time response speed, while giving a smoother difficulty.  But after further thought, I believe the on-off attacks are more in block time than real time. So N=25 to make it loo most like Zcash in block time.

**Details of max gain from bad timestamps**
This attack requires > 50% mining to get past the MTP protection.  With max 10% drop, if he's only 50% hashrate, he can only get FTL/T blocks at an average 5% below previous D, before he has "bumped into the FTL".  Note that D is supposed to be 2x higher if he jumps on with 50% HR instead of 5% lower.  With 10% max drop and a 100x network hashrate, it allows him an average 5% lower D for damp\*N/2 blocks before D starts rising (he's so fast at getting blocks, bumping into the FTL is not the problem as much as the algorithm finally responding to seeing the same highly-forwarded timestamp in every block).  

**Allows MTP delay to be removed**
This falls under "if you have time".
With such a tight forward constraint (and the MTP reverse time limit) timestamp manipulation benefits are all but stopped (not counting the "100x" attacker (or 20x) mentioned above), so the MTP delay for the window is not needed, which would have a large benefit by enabling the DA to rise 6 blocks faster in response to on-off mining.  A monero dev argued with me saying "we do not consider >50% HR problems as relevant because they can do selfish mining or other 51% attacks anyway".  However, extensive experience in micro coins is that they will almost always happily mine without causing any problems other than timestamp manipulation.  There's an implicit belief similar to the monero dev's position in using the MTP: it stops any problem from < 50% miners, and it seems like I was told "there's nothing we can do about > 50% mining anyway" in regards to the MTP delay.

**Caution:** the effects of this change are not something I can claim to be an expert in.   Why did BTC devs decide on a largish value of 2 hours, aka 12xT?  Something to do with daylight saving's change?   Block propagation? Chain re-orgs? (I think it might have been instituted after the original complicated "timewarp" attack that depended on BTC not having a rolling average).  Why were Zcash devs reluctant to lower it below say 1000 (judging from a comment @daira made)? This change is at the core of the POW timestamp server method where the winning miner gets to say what time it is rather than the nodes.  However, the comments of about 4 small coin devs was that it should not be a problem. Two were like "not a problem", and 2 were like "probably not a problem". About 10 others did not know enough to offer an opinion or were silent.  So I went ahead with this as a recommendation because the benefits are large. The risk from not doing it seemed greater.  So far we have not seen a problem (about 25 coins would have either notified me, or I would have found out from my monitoring).  It's like several years of live testing, minus the coming fall daylight savings change.

**Comment by tromp** [comment] 2018-08-03 14:22
> If you make FTL 360, then you could lower N=25 and max D drop would be 7.5%.
> I think a drop of 10% is OK. N=60 verses N=25 is a very complicated
> decision. If the coin is going to be the largest for the given POW, then
> N=60.

We're expecting ASICs in the long run, and have a good shot at being
the number 1 Cuckoo Cycle coin, so let's be optimistic and see how N=60 goes.


 Otherwise I'm for N=25 because it's a lot like Zcash in block time and
> that's the 2nd best algo being used all the way from Zcash down to small
> coins. My previous comments saying N=60 is like Zcash is only about real
> time response speed, while giving a smoother difficulty. But after further
> thought, I believe the on-off attacks are more in block time than real time.
> So N=25 to make it loo most like Zcash in block time.

> Allows MTP delay to be removed
> This falls under "if you have time".
> With such a tight forward constraint (and the MTP reverse time limit)
> timestamp manipulation benefits are all but stopped (not counting the "100x"
> attacker (or 20x) mentioned above), so the MTP delay for the window is not
> needed, which would have a large benefit by enabling the DA to rise 6 blocks
> faster in response to on-off mining. A monero dev argued with me saying "we
> do not consider >50% HR problems as relevant because they can do selfish
> mining or other 51% attacks anyway". However, extensive experience in micro
> coins is that they will almost always happily mine without causing any
> problems other than timestamp manipulation. There's an implicit belief
> similar to the monero dev's position in using the MTP: it stops any problem
> from < 50% miners, and it seems like I was told "there's nothing we can do
> about > 50% mining anyway" in regards to the MTP delay.

The 11 block median seems quite generous to me. I wouldn't mind
something a little smaller,
like median of 7. But this presumes you allow timestamps to decrease
from one block to the next,
If you require non-decreasing timestamps then there seems to be no
point in MPT delay.

> Caution: the effects of this change are not something I can claim to be an
> expert in. Why did BTC devs decide on a largish value of 2 hours, aka 12xT?

Because their 2016 block retargeting window already prevents all
timestamp manipulation.

> Something to do with daylight saving's change?

Yes, I suspect they wanted to be forgiving of DST and other timezone quirks.

regards,
-John

**Comment by zawy12** [comment] 2018-08-03 14:40
OK, so if we stick with N=60, the FTL=720 is fine and 1/2 and 2x should be fine, so no change is needed.  I'll be interested in seeing how the N=60 does.  You will probably be happy with it being smoother than zcash, and probably there will not be a problem.

**Comment by tromp** [comment] 2018-10-14 07:17
Let's close this as soon as the related https://github.com/mimblewimble/grin/issues/1486 is resolved.

**Comment by zawy12** [comment] 2018-10-14 13:03
@daira I balk when people say or imply >50% hashrate attacks are not addressable.

Small coins often have to daily deal with 20x their baseline hashrate jumping on and off. If they have a difficulty algorithm problem, they will get attacked severely until they either die or fix the problem.  >75% miners is the rule in the small coin world, but the only problem is an occasional double spending attack on exchanges. Cryptopia might have 10 coins that recently experienced double spends, the ones listed as "network issues" when you do a sort on zero price and zero price change to narrow your search down.

To quote myself in another issue:

> Some people think >50% attacks are not relevant because they are not addressable, but > 50% attacks will almost never occur in any coin if the difficulty algorithm is optimal, but will occur on almost any coin where it is not. For example, the lack of an optimal algorithm in Zcash has resulted in 66% to 80% hashrate attacks about twice a day <strike>since it began</strike> in the first year I was checking it, merely getting 30 to 50 blocks a day at a 30% discount compared to the other miners.  Almost no one notices or complains, so it's not hardly a problem.   Small coins with larger holes to >50% attacks will soon get severely attacked (difficulty is forced lower with timestamp manipulation, or difficulty is too slow to respond) until they either die (almost every Cryptonote and Monero clone that did not change it's difficulty algorithm) or fork to get a new algorithm.  A good DA can survive 10x to 50x hashrate attacks without a problem other than 1 to 3 slow blocks post-attack, discouraging the attacks from happening again.

**Comment by hashmap** [comment] 2019-06-14 22:15
Closing, no active discussions for a while

**Closed by hashmap** 2019-06-14 22:15 UTC
Labels: question, research
