### ISSUE TITLE
Grin uses deprecated `time` crate

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin#783] opened 2018-03-15 12:24 UTC
For example in BlockHeader:

```
	/// Timestamp at which the block was built.
	pub timestamp: time::Tm,
```

Which may be ok per se, unfortunately I found a bug during fuzz tests (at least on OSX):
```
thread '<unnamed>' panicked at 'gmtime_r failed: Value too large to be stored in data type (os error 84)', /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.39/src/sys.rs:273:17
...
 #13 0x10ae67fdf in time::sys::inner::time_to_utc_tm::haccd130fa42a2309 sys.rs:273
    #14 0x10ae3fd85 in time::at_utc::h2475696bedb92f2a lib.rs:404
    #15 0x10a52c43a in _$LT$grin_core..core..block..BlockHeader$u20$as$u20$grin_core..ser..Readable$GT$::read::_$u7b$$u7b$closure$u7d$$u7d$::h7685abd8874970d6 block.rs:192
...
```

This code reproduces this bug:

```
extern crate time;

fn main() {
	let _t =  time::at_utc(time::Timespec {
				sec: std::i64::MAX,
				nsec: 0,
	});
}
```
It looks gross, type system is clearly misused here. Btw libc docs sound strange:
``` 
In the GNU C library and other POSIX-compliant implementations, time_t is equivalent to long int. 
...
In the GNU C Library, time_t is equivalent to long int. In other systems, time_t might be either an integer or floating-point type. 
```

Bottom line - should we migrate to `chrono`?

**Comment by yeastplume** [comment] 2018-03-15 15:56
I'm not sure I understand what the issue is.. the code you've included there to reproduce looks like it's behaving correctly (failing with an error), as you've set the seconds field in the time spec to its max i64 value which means you've hit the end of 64-bit time. If there's an OS-specific issue somewhere that's not reporting the time correctly, then it definitely needs to be looked at but we need to isolate what it is exactly before switching libraries. The rust time crate we're using is up to date, if you check in cargo.log you can see it resolves to the latest version.

The most important thing is the serialisation of the field, which is epoch time in seconds+nanoseconds, so if some OS call isn't populating that properly then there is indeed a bug.

**Comment by hashmap** [comment] 2018-03-15 16:37
Basically one can send a block and crash Grin node. The code panics, also `std::i64::MAX-100_000` produces the same result.
The crate is up to date, however it's deprecated in favor of `chrono` (https://github.com/rust-lang-deprecated/time)

**Comment by yeastplume** [comment] 2018-03-15 16:50
Okay, that makes sense then.. the time crate is a bit confusing because the main page says is deprecated but the code's been updated as recently as 2 months ago. No problem with using chrono if that's the case.

**Comment by ignopeverell** [comment] 2018-03-15 18:38
I'm less concerned with the time crate than with the crash. Pushed a fix to bound the time to 2^60.

**Closed** 2018-03-15 18:37 UTC
