### ISSUE TITLE
v1.0.3 fails to build grin binary

### ISSUE THREAD

**Issue by jorgeelmundoso** [mimblewimble/grin#2894] opened 2019-06-12 14:43 UTC
**Describe the bug**
Grin v1.0.3 fails to build since 3 days.

**To Reproduce**
```
git clone --recursive --depth=1 https://github.com/mimblewimble/grin.git -b v1.0.3
cd grin
docker build -t grin -f etc/Dockerfile .
```

**Relevant Information**
```
   Compiling tokio-tcp v0.1.3
   Compiling tokio-udp v0.1.3
   Compiling croaring-sys v0.3.8
   Compiling mortal v0.1.5
   Compiling grin_keychain v1.0.3 (/usr/src/grin/keychain)
error[E0204]: the trait `Copy` may not be implemented for this type
   --> keychain/src/extkey_bip32.rs:152:10
    |
152 | #[derive(Copy, Clone, PartialEq, Eq, Debug)]
    |          ^^^^
...
163 |     pub secret_key: SecretKey,
    |     ------------------------- this field does not implement `Copy`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0204`.
error: Could not compile `grin_keychain`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 
 - Version 10.13.6 
 - Docker Desktop Version 2.0.0.3 (31259) 

**Additional context**
Image was build via docker

**Comment by quentinlesceller** [comment] 2019-06-12 17:05
Indeed, I can confirm. And it's not a docker thing, I'm unable to build v1.0.3 because of this.

**Comment by quentinlesceller** [comment] 2019-06-12 18:30
Okay so if you really want to build v1.0.3 by yourself you'll need to force it to use the exact `rust-secp256k1-zkp`.
Basically modify `util/Cargo.toml` like that
```
-version = "0.7.5"
+version =  "=0.7.5"
```

Closing.

**Closed by quentinlesceller** 2019-06-12 18:30 UTC
Labels: bug

**Comment by nitronick600** [comment] 2019-06-13 07:07
Modifying util/Cargo.tomly fixed my issue.

**Comment by jorgeelmundoso** [comment] 2019-06-13 08:31
Maybe if it's worth push a fix to that tag, but i guess that would be mostly for historical reasons
