### ISSUE TITLE
grin v5.0.1 core dumped

### ISSUE THREAD

**Issue by etherclement** [mimblewimble/grin#3548] opened 2021-01-20 03:30 UTC
**Describe the bug**
grin node crashed, log:
```bash
 memory allocation of 137438953472 bytes failedAborted (core dumped)    
```                                                                                                                          
**To Reproduce**
grin --testnet server run

**Desktop:**
 - OS: ubuntu 18.04
 - Mem: 32G

**Comment by trevyn** [comment] 2021-03-19 02:22
Hi @etherclement ! Unfortunately, I can't reproduce this.

- Are you still experiencing this crash?
- If so, from what source did you install grin and what does `grin --version` show?
- Did this happen from a fresh install or were you able to get grin started, and then this occurred later?
- Does moving or renaming the `~/.grin` directory and trying again help?

Thanks!

**Comment by yeastplume** [comment] 2022-01-07 13:35
Closing for lack of follow-up.

**Closed by yeastplume** 2022-01-07 13:35 UTC
