### ISSUE TITLE
Wallet lost coinbase output

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2886] opened 2019-06-10 00:57 UTC
**Describe the bug**
Pool found block:
  Height: 208377
  Hash: 00000231945d

It appears to be accepted by the blockchain (not orphaned):
  https://grinexplorer.net/block/00000231945d1c88998d22fa5e31374f23e51ae21f1d2bb85c40612931165409

But our wallet has no output for this block:
```
# grin wallet outputs
...
20190610 00:47:49.239 DEBUG grin_wallet::libwallet::internal::updater - Refreshing wallet outputs
...
 Output Commitment                                                   MMR Index  Block Height  Locked Until  Status   Coinbase?  # Confirms  Value          Tx
================================================================================================================================================================
...
 09024ba41ebf2811d75d114a3eec436410408d7a7c68118bb2eb6d30da894e4e19  None       208174        209614        Unspent  true       305         60.000000000   3953
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 0949125ab9be0709d65dc25b13a07950db9f0e77dfcadb8209e40471bcb590d1c9  None       208046        0             Unspent  false      433         25.452570306   3951
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 080863414c6dc353d9b991c35fd58280bfeaed45113f4ec26ce5efde9b7b82f5a2  None       208255        0             Unspent  false      224         2.059922200    3954
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 09da86f73edcffb9cb4ecfc82e0e18767d10408e05bf84caba5ad272bec784591d  None       208479        209919        Mining   true       0           60.007000000
----------------------------------------------------------------------------------------------------------------------------------------------------------------

Command 'outputs' completed successfully
```

**Relevant Information**
```
# grin --version
grin 1.0.3
```

**Additional context**
Wallet logs for generating the coinbase:
```
20190609 23:09:03.751 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120f00000000), 0300000000000000000000120f00000000
20190609 23:09:03.751 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120f00000000)) }
20190609 23:09:03.831 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190609 23:09:03.868 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120f00000000), 0300000000000000000000120f00000000
20190609 23:09:03.868 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120f00000000)) }
20190609 23:09:03.973 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190609 23:09:04.016 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120f00000000), 0300000000000000000000120f00000000
20190609 23:09:04.016 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120f00000000)) }
20190609 23:09:04.081 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190609 23:09:04.112 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120500000000), 0300000000000000000000120500000000
20190609 23:09:04.112 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120500000000)) }
20190609 23:09:04.193 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190609 23:09:04.223 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120f00000000), 0300000000000000000000120f00000000
20190609 23:09:04.223 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120f00000000)) }
20190609 23:09:04.304 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190609 23:09:04.333 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120f00000000), 0300000000000000000000120f00000000
20190609 23:09:04.333 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120f00000000)) }
20190609 23:09:04.421 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190609 23:09:04.455 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120f00000000), 0300000000000000000000120f00000000
20190609 23:09:04.455 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120f00000000)) }
20190609 23:09:04.594 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190609 23:09:04.646 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120f00000000), 0300000000000000000000120f00000000
20190609 23:09:04.646 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 22000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120f00000000)) }
20190609 23:09:04.748 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20190609 23:09:04.793 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000120500000000), 0300000000000000000000120500000000
20190609 23:09:04.793 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 208377, key_id: Some(Identifier(0300000000000000000000120500000000)) }
```

Grin server logs for finding the block:
```
20190609 23:09:24.346 DEBUG grin_chain::pipe - pipe: process_block 00000231945d at 208377 [in/out/kern: 4/5/3]
20190609 23:09:24.348 DEBUG grin_chain::pipe - pipe: header_head updated to 00000231945d at 208377
20190609 23:09:24.377 DEBUG grin_chain::pipe - pipe: head updated to 00000231945d at 208377
20190609 23:09:24.382 DEBUG grin_servers::common::adapters - block_accepted (head+): 00000231945d at 208377 (diff: 595385526300270)
20190609 23:09:24.384 DEBUG grin_p2p::peers - broadcast_compact_block: 00000231945d, 595385526300270 at 208377, to 150 peers, done.
20190609 23:09:24.392 WARN grin_servers::mining::stratumserver - (Server ID: 0) Solution Found for block 208377, hash 00000231945d - Yay!!! Worker ID: 2, blocks found: 1, shares: 198063
20190609 23:09:24.392 INFO grin_servers::mining::stratumserver - (Server ID: 0) Got share at height 208377, hash 00000231945d, edge_bits 29, nonce 2308516029356649892, job_id 2, difficulty 11961491299/3166372898, submitted by GrinPool
20190609 23:09:24.931 DEBUG grin_chain::txhashset::txhashset - Rewind to header 00000231945d at 208377
```

**Comment by bladedoyle** [comment] 2019-06-10 01:18
After a wallet restore from seed and check, I think I do see the coinbase in the restored wallet:
```
 08696f33eeeb014bb3378adc74dfb7bd264e7208c78abc507e0d157754d76a01d1  2466318    208377        209817        Unspent  true       126         60.014000000   126 
```

**Comment by kargakis** [comment] 2019-06-10 16:59
@bladedoyle can this issue be closed then?

**Comment by quentinlesceller** [comment] 2019-06-14 14:17
For the record this issue also appears frequently on Grinmint. We regularly do wallet restore to recover those "lost" coinbases. I was not able to identify the root cause of this and I've no evidence so far that it was fixed in v1.0.3+. Leaving it open for now.

**Comment by shrikus** [comment] 2019-07-12 10:36
confirming same issue with 2.0 wallet. some coinbase outputs showing in wallet only after 'check' command.

**Comment by bladedoyle** [comment] 2019-08-29 04:17
Bump.   My 2.0 wallet continues to lose coinbase outputs.   
This is hard to deal with combined with the wallet locking issues described in https://github.com/mimblewimble/grin-wallet/issues/148 since "online" wallet can not run check.

**Comment by quentinlesceller** [comment] 2019-09-04 14:07
Issue opened in grin-wallet repo: https://github.com/mimblewimble/grin-wallet/issues/214.

**Closed by quentinlesceller** 2019-09-04 14:07 UTC
