### ISSUE TITLE
Being forked off rather frequentely while mining on testnet1

### ISSUE THREAD

**Issue by mably** [mimblewimble/grin#704] opened 2018-02-12 21:44 UTC
Sadly, I have no idea why this is happening.

A 20 mns log file excerpt around today's fork:

https://gist.github.com/mably/213720f034395c51c996455faf4dc51a

It looks like my node never received the block 69448.

If I disable mining, I can get back on the right chain and reactivate mining.

But it would fork again a few hours later.  It's been happening since about one week I think.

**Comment by ignopeverell** [comment] 2018-02-12 23:39
This seems to be caused by the 2 different issues:

1. As you mentioned, you missed 69448. When you received 69449, as it was found to be orphaned, it would be good if we had asked for 69448. Going to file a separate improvement for that.
2. Mining power on testnet1 is very low right now, so you never reach a point where you're far enough to re-trigger sync.

That 2nd point shouldn't matter on testnet2 and even less so on mainnet. But we should be able to do something about the first.

**Comment by ignopeverell** [comment] 2018-02-12 23:59
Closing this, as it's superseded by #705

**Closed by ignopeverell** 2018-02-12 23:59 UTC
Labels: bug
